input-output-hk/mantis

- build.sbt
- src/it/scala/io/iohk/ethereum/mpt/MerklePatriciaTreeIntegrationSuite.scala
- src/main/scala/io/iohk/ethereum/mpt/EphemDataSource.scala
- src/test/scala/io/iohk/ethereum/mpt/MerklePatriciaTrieSuite.scala
In order to avoid long running tests to be ignored (or bother local executions) we decided to split them in two different configurations. Test can be run as:
- `sbt test` will run faster tests 
- `sbt it:test` will run benchmark and integration tests that take more time to run
`it` configuration was based on `Test` to be able to share `ObjectGenerators` and maybe any other test utils class. Please let me know if you don't like it.
I also created an `EphemDataSource` as after several discussions this will be needed besides tests. We can create a custom for testing purposes in the future. Will add tests for this and IodbDataSource once this PR is merged.
> [MPT] Test partitioning in order not to ignore long running tests

- src/main/scala/io/iohk/ethereum/network/PeerActor.scala
- src/main/scala/io/iohk/ethereum/network/p2p/messages/PV62.scala
- src/main/scala/io/iohk/ethereum/network/p2p/validators/ForkValidator.scala
- src/main/scala/io/iohk/ethereum/network/p2p/validators/MessageValidator.scala
- src/test/scala/io/iohk/ethereum/network/p2p/validators/ForkValidatorSpec.scala
The client will connect only to an ETC supporting client. In order to do so, after handshake Dao BlockHeaders is requested in order to compare it's hash with the ETC fork one.
If the other peer does not return the block we have a simplification about the one stated [here](https://github.com/ethereum/go-ethereum/pull/2795). We are not currently checking our blockchain but comparing DaoBlock total difficulty (TD) against other node TD as this is and indicator for the longest chain. That being said, this tweak should not break thingsbecause the node sync process will disconnect from that peer if DAO block is found.
Note1: our client node status is hardcoded and needs to be changed during the next sprints
Note: BlockHeader validation logic was encapsulated in order to be re-used by @adamsmo …
> [EC-32] Classic Chain Check 

- src/main/scala/io/iohk/ethereum/network/p2p/messages/CommonMessages.scala
- src/test/scala/io/iohk/ethereum/rlp/RLPSpeedSuite.scala
- src/test/scala/io/iohk/ethereum/rlp/RLPSuite.scala
- Some Test classes added to test RLP encoding were replaced by real implementations (made after some sprints)
- There are still missing ones like `Block`. 
- Test implementations were renamed to `TestXXXXX` to avoid confusions while coding
- `FIXME` comments were added so we can replace them in the future
> Remove old fake types implementations

- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/network/PeerActor.scala
- src/main/scala/io/iohk/ethereum/network/p2p/validators/ForkValidator.scala
- src/main/scala/io/iohk/ethereum/utils/Config.scala
- src/test/scala/io/iohk/ethereum/network/p2p/PeerActorSpec.scala
When connection is initiated we try to check if peer is running ETC fork.
* it is - we keep connection
* it is not, but we're not at a fork yet - we can download some blocks until fork, thus we keep connection
* it is not at the fork yet - we keep the connection
* it is not running ETC (and we're after the fork) - disconnect
Then, when connected, we check if received block header is a fork header, if so, we validate it and if it's not ETC fork we disconnect. Hope that makes sense.
> [EC-45] Add dao fork check

- src/main/scala/io/iohk/ethereum/vm/OpCode.scala
- src/main/scala/io/iohk/ethereum/vm/Storage.scala
- src/test/scala/io/iohk/ethereum/vm/StorageSpec.scala
If a `DataWord.Zero` is passed as a value to a `Storage` then a corresponding key should removed from the underlying hashmap.
> Bugfix in Storage and updates of docs.

- src/it/scala/io/iohk/ethereum/db/IodbDataSourceIntegrationSuite.scala
- src/it/scala/io/iohk/ethereum/mpt/MerklePatriciaTreeIntegrationSuite.scala
- src/main/scala/io/iohk/ethereum/db/dataSource/DataSource.scala
- src/main/scala/io/iohk/ethereum/db/dataSource/EphemDataSource.scala
- src/main/scala/io/iohk/ethereum/db/dataSource/IodbDataSource.scala
- src/test/scala/io/iohk/ethereum/db/dataSource/EphemDataSourceSuite.scala
- src/test/scala/io/iohk/ethereum/db/storage/CodeStorageSuite.scala
- src/test/scala/io/iohk/ethereum/db/storage/KeyValueStorageSuite.scala
- src/test/scala/io/iohk/ethereum/db/storage/MptNodeStorageSuite.scala
- src/test/scala/io/iohk/ethereum/db/storage/NodeStorageSuite.scala
- src/test/scala/io/iohk/ethereum/db/storage/ReceiptStorageSuite.scala
- src/test/scala/io/iohk/ethereum/mpt/MerklePatriciaTrieSuite.scala
- Added `clear` function to DataSource, to remove all the data from it.
- Added `close` function to DataSource, to close the DataSource.
- Added `destroy` function to DataSource, that closes it and deletes all the data from it.
- Added checking of the keys length in the `get` and `update` functions of IODB (as discussed in #31 ).
- Added option to use a previously closed (but not destroyed) `IodbDataSource` when creating one. This is now done instead of deleting the folder by default.
- As IODB doesn't yet provide functionality to easily clear it, the DataSource is destroyed and created again.
> [EC-60] Remove all data from DataSource

- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/domain/SignedTransaction.scala
- src/main/scala/io/iohk/ethereum/utils/Config.scala
- src/test/scala/io/iohk/ethereum/network/p2p/messages/TransactionSpec.scala
This PR adds support for new signing scheme for chain specific transactions added by 
this EIP
https://github.com/ethereum/EIPs/issues/155
fork block number is not yet set but we are receiving transactions that are signed according to that proposal.
`0x3d` is blockchain id for ethereum classic
> [EC-72] change signing scheme for chain specific transactions

- src/main/scala/io/iohk/ethereum/App.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSyncBlockBodiesRequestHandler.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSyncBlockHeadersRequestHandler.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSyncController.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSyncReceiptsRequestHandler.scala
- src/main/scala/io/iohk/ethereum/db/components/DataSourcesComponent.scala
- src/main/scala/io/iohk/ethereum/db/components/SharedEphemDataSources.scala
- src/main/scala/io/iohk/ethereum/db/components/SharedIodbDataSources.scala
- src/main/scala/io/iohk/ethereum/db/components/SharedLevelDBDataSources.scala
- src/main/scala/io/iohk/ethereum/db/components/Storages.scala
- src/main/scala/io/iohk/ethereum/db/components/StoragesComponent.scala
- src/main/scala/io/iohk/ethereum/db/storage/AppStateStorage.scala
- src/main/scala/io/iohk/ethereum/db/storage/KeyValueStorage.scala
- src/main/scala/io/iohk/ethereum/domain/Blockchain.scala
- src/main/scala/io/iohk/ethereum/network/BlockBroadcastActor.scala
- src/main/scala/io/iohk/ethereum/network/FastSyncHost.scala
- src/main/scala/io/iohk/ethereum/network/PeerActor.scala
- src/main/scala/io/iohk/ethereum/network/PeerManagerActor.scala
- src/main/scala/io/iohk/ethereum/utils/NodeStatus.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/FastSyncBlockBodiesRequestHandlerSpec.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/FastSyncBlockHeadersRequestHandlerSpec.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/FastSyncControllerSpec.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/FastSyncReceiptsRequestHandlerSpec.scala
- src/test/scala/io/iohk/ethereum/network/PeerManagerSpec.scala
- src/test/scala/io/iohk/ethereum/network/p2p/BlockBroadcastActorSpec.scala
- src/test/scala/io/iohk/ethereum/network/p2p/PeerActorSpec.scala
Add storage for most recent fully downloaded (with body and receipts) block. Use that to resume fast sync where we left off.
> [EC-117] Resume blockchain download on app restart

- src/main/resources/logback.xml
- src/universal/conf/logback.xml
Use rolling file appender for both `sbt run` and `sbt dist` and make the `logback` in `sbt dist` the same as in `run` in order to effectively debug.
> Add Rolling file appender

- src/main/resources/reference.conf
Issue is related to too big message containing receipts, fix for now is to limit number of receipts that can be send with one message
Final fix is adding support for multi frame messages
> [EC-143] Code throws 'data too short' exception regularly

- src/it/scala/io/iohk/ethereum/db/DataSourceIntegrationTestBehavior.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSyncNodesRequestHandler.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/RegularSync.scala
- src/main/scala/io/iohk/ethereum/common/SimpleMap.scala
- src/main/scala/io/iohk/ethereum/mpt/MerklePatriciaTrie.scala
- src/main/scala/io/iohk/ethereum/network/PeerActor.scala
- src/main/scala/io/iohk/ethereum/vm/Program.scala
- src/main/scala/io/iohk/ethereum/vm/ProgramState.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/SyncControllerSpec.scala
- src/test/scala/io/iohk/ethereum/db/dataSource/DataSourceTestBehavior.scala
- src/test/scala/io/iohk/ethereum/ledger/BlockRewardSpec.scala
- src/test/scala/io/iohk/ethereum/network/p2p/PeerActorSpec.scala
Includes several fixes to issues detected while running different static analysis tools.
The main problems fixed were:
* Changed `Seq()` and `Seq.empty` to `Nil`.
* Changed `Set()` to `Set.empty`.
* Refactoring mentioned in #102 comments.
> Static analysis fixes

- src/main/scala/io/iohk/ethereum/domain/SignedTransaction.scala
- src/main/scala/io/iohk/ethereum/ledger/BloomFilter.scala
- src/main/scala/io/iohk/ethereum/ledger/InMemoryWorldStateProxy.scala
- src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
- src/main/scala/io/iohk/ethereum/validators/BlockValidator.scala
- src/test/scala/io/iohk/ethereum/ledger/InMemoryWorldStateProxySpec.scala
- src/test/scala/io/iohk/ethereum/network/p2p/messages/TransactionSpec.scala
- src/test/scala/io/iohk/ethereum/validators/BlockValidatorSpec.scala
Includes fixes to several issues that where detected during tx execution, this includes:
* Before running `validateBlockAfterExecution` we persist the trie (so as to obtain the correct state root hash).
* The state trie is now a secure trie (the keys are hashed before inserting them).
* Fixing how the sender is recovered from a transaction (in https://github.com/ethereum/ethereumj/blob/develop/ethereumj-core/src/main/java/org/ethereum/crypto/ECKey.java#L439 the head of the public key is dropped).
* Fixed in `BlockValidator.validateLogBloom` how we handle the case where there are no receipts.
> Fixed bugs in tx execution

- src/evmTest/scala/io/iohk/ethereum/vm/utils/EvmTestEnv.scala
- src/main/scala/io/iohk/ethereum/domain/Address.scala
- src/main/scala/io/iohk/ethereum/domain/SignedTransaction.scala
- src/main/scala/io/iohk/ethereum/domain/Transaction.scala
- src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
- src/main/scala/io/iohk/ethereum/network/p2p/messages/CommonMessages.scala
- src/main/scala/io/iohk/ethereum/vm/ProgramContext.scala
- src/main/scala/io/iohk/ethereum/vmrunner/MockVmInput.scala
- src/main/scala/io/iohk/ethereum/vmrunner/State.scala
Includes fixes to the bugs:
* Both `Ledger.updateSenderAccountBeforeExecution` and `ProgramContext.callOrCreate` decreased tx.value from sender of a tx in the state world so the sender's balance was decreased by `tx.value` twice
* In case a tx was for contract creation (so `receivingAddress` was empty) the `recevingAdress` was padded with zeros (resulting in the address `0x00000000000000000000` instead of an empty one). This changed the result of encoding the `SignedTransaction`for `BlockValidator.validateTransactionRoot`. The `tx.recevingAddress` was changed to an `Option[Address]` with `None` signifying that the tx is for contract creation.
> Fixed more bugs in tx execution

- src/it/scala/io/iohk/ethereum/mpt/MerklePatriciaTreeIntegrationSuite.scala
- src/main/scala/io/iohk/ethereum/mpt/MerklePatriciaTrie.scala
- src/test/scala/io/iohk/ethereum/mpt/MerklePatriciaTrieSuite.scala
This commit removes old mpt nodes deletion from underlying db. From now on, a pruning system needs to be performed in order to free space.
Mpt now doesn't _know_ that some nodes are useless now. If we think our pruning implementation requires to record "deletes" - for example if it's made using reference counting method - this commit can be rolled back.
> [EC-156] Remove erasing of nodes in MPT

- src/evmTest/scala/io/iohk/ethereum/vm/utils/EvmTestEnv.scala
- src/main/scala/io/iohk/ethereum/vm/OpCode.scala
- src/main/scala/io/iohk/ethereum/vm/ProgramContext.scala
- src/main/scala/io/iohk/ethereum/vm/WorldStateProxy.scala
- src/main/scala/io/iohk/ethereum/vmrunner/State.scala
- src/test/scala/io/iohk/ethereum/ledger/LedgerSpec.scala
- src/test/scala/io/iohk/ethereum/vm/CreateOpcodeSpec.scala
Includes a fix to nonce being increased twice in contract creation (before it was increased both in `WorldState.newAddress` and `Ledger.updateSenderAccountBeforeExecution`).
> [EC-159] Fixed nonce being increased twice in contract creation

- src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
- src/main/scala/io/iohk/ethereum/vm/EvmConfig.scala
- src/test/scala/io/iohk/ethereum/ledger/LedgerSpec.scala
We need this logic in two places: CREATE op code (already there) and Ledger (this PR).
> Handle pre-Homestead contract creation when not enough gas

- src/main/scala/io/iohk/ethereum/ledger/InMemoryWorldStateProxy.scala
- src/test/scala/io/iohk/ethereum/ledger/InMemoryWorldStateProxySpec.scala
At block #49157 a SSTORE operation to `address 1` with a `UInt256.Zero` value was being called. When doing so, instead of removing data from `address 1` we were storing the `UInt256.Zero`
- [Tx Link](https://live.ether.camp/transaction/e9b2d3e8a2bc996a1c7742de825fdae2466ae783ce53484304efffe304ff232d)
- [Code being executed](https://live.ether.camp/transaction/e9b2d3e8a2bc996a1c7742de825fdae2466ae783ce53484304efffe304ff232d/vmtrace#41)
Always, when storing `UInt256.Zero` in contract storage, we should remove that _row_ from the underlying trie.
This leads to execution up to block #49439
> Store zero contract storage error

- src/test/scala/io/iohk/ethereum/blockchain/sync/SyncControllerSpec.scala
The failing test was:
```
[info] - should only broadcast blocks that it was able to successfully execute *** FAILED *** (104 milliseconds)
[info]   java.lang.AssertionError: assertion failed: not found [Subscribe(Set(20))]
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.testkit.TestKitBase.checkMissingAndUnexpected(TestKit.scala:543)
[info]   at akka.testkit.TestKitBase.expectMsgAllOf_internal(TestKit.scala:551)
[info]   at akka.testkit.TestKitBase.expectMsgAllOf(TestKit.scala:537)
[info]   at akka.testkit.TestKitBase.expectMsgAllOf$(TestKit.scala:537)
[info]   at akka.testkit.TestKit.expectMsgAllOf(TestKit.scala:814)
[info]   at io.iohk.ethereum.blockchain.sync.SyncControllerSpec$$anon$8.<init>(SyncControllerSpec.scala:461)
[info]   at …
```
> increase test timeout

- src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
- src/test/scala/io/iohk/ethereum/ledger/LedgerSpec.scala
At block #53145 an `InvalidJump` error is returned and the Receipts validation is failing.
When an error is returned logs should be cleared as it's done [here](https://github.com/paritytech/parity/blob/master/ethcore/src/executive.rs#L497), making the receipts match the ones in the blockHeader
This leads to execution up to block #62102
_Note: This PR needs this one https://github.com/input-output-hk/etc-client/pull/147 to be merged first_
> Logs should be cleared after an error is returned when executing a TX

- src/main/scala/io/iohk/ethereum/vm/OpCode.scala
At block #62102 there is a call to the op `MOD` and `SMOD` is being executed instead
Update `SMOD` (and the following) opcodes in order to match the ones stated in YP.
This leads to execution up to block #68460
> Fix wrong opCodes number assignment

- src/main/scala/io/iohk/ethereum/domain/Receipt.scala
- src/main/scala/io/iohk/ethereum/domain/SignedTransaction.scala
- src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
- src/main/scala/io/iohk/ethereum/rpc/BlockController.scala
- src/main/scala/io/iohk/ethereum/vm/VM.scala
This PR has some logging statements that will help while debugging the app. 
```
12:57:46.880 io.iohk.ethereum.ledger.LedgerImpl - Transaction e310dde4735aa6ab90d69910aacdce77ad399db3f94a5b4bba93fa01df353a08 execution start
12:57:46.881 io.iohk.ethereum.vm.VM$ - CALLDATASIZE | pc: 1 | depth: 0 | stack: Stack(0)
12:57:46.881 io.iohk.ethereum.vm.VM$ - PUSH1 | pc: 3 | depth: 0 | stack: Stack(0,0)
12:57:46.881 io.iohk.ethereum.vm.VM$ - DUP1 | pc: 4 | depth: 0 | stack: Stack(0,0,0)
12:57:46.881 io.iohk.ethereum.vm.VM$ - CALLDATACOPY | pc: 5 | depth: 0 | stack: Stack()
12:57:46.881 io.iohk.ethereum.vm.VM$ - PUSH1 | pc: 7 | depth: 0 | stack: Stack(32)
12:57:46.881 io.iohk.ethereum.vm.VM$ - PUSH1 | pc: 9 | depth: 0 | stack: Stack(0,32)
12:57:46.881 io.iohk.ethereum.vm.VM$ - CALLDATASIZE | pc: 10 …
```
> Logs improved in order to help when debugging errored tx executions

- src/main/scala/io/iohk/ethereum/vm/OpCode.scala
- src/test/scala/io/iohk/ethereum/vm/CallOpcodesSpec.scala
- src/test/scala/io/iohk/ethereum/vm/CreateOpcodeSpec.scala
At block 81383 there is a CALL opcode to a contract where several SSTORE opcodes are called, some of which result in gas being added to be refunded (that is `ProgramState.gasRefund` is increased). In the code of the `CallOp`s this `gasRefund` from the `ProgramResult` of the call to the contract wasn't being added to the gas to be refunded.
This for example is done in EthereumJ in https://github.com/ethereum/ethereumj/blob/master/ethereumj-core/src/main/java/org/ethereum/vm/program/Program.java#L571.
Update the `CallOp`s so that the gas refunded in the contract being called are passed to the caller of them.
With this fix we are able to execute all blocks till block 153259.
_Note_: It also includes the same fix applied to the CREATE opcode, which means that the `ProgramResult.gasRefund` of …
> Fix gas refund from contract called not passed to caller/creator

- src/main/scala/io/iohk/ethereum/vm/ProgramContext.scala
- src/test/scala/io/iohk/ethereum/ledger/LedgerSpec.scala
At block #153259 a contract init is being called and the resulting gas does not match.
When it's a contract init transaction, payload shouldn't be used as ExecEnv inputData. YP eq 91
This leads to block #179332
> Fix evm inputData when executing contract init transaction

- src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
- src/test/scala/io/iohk/ethereum/ledger/LedgerSpec.scala
At Block #243826 When executing a contract init, tx fails because the account already exists
As stated in YP EIP-150 REVISION eq 86 the destination address might have already received funds .
This leads up to #244793 execution.
> Fix for contract init that might be using an account that already exists

- src/main/scala/io/iohk/ethereum/vm/Memory.scala
- src/test/scala/io/iohk/ethereum/vm/OpCodeFunSpec.scala
This PR changes property test to correctly check memory size.
Corner case related to EC-168 is tested in https://github.com/input-output-hk/etc-client/blob/phase/3/txExecution/src/test/scala/io/iohk/ethereum/vm/MemorySpec.scala#L161
> [EC-168] Isolate failing edge case found in property test for evm op code RETURN

- src/evmTest/resources/solidity/CallSelfDestruct.sol
- src/evmTest/scala/io/iohk/ethereum/vm/CallSelfDestructSpec.scala
- src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
- src/main/scala/io/iohk/ethereum/vm/OpCode.scala
- src/main/scala/io/iohk/ethereum/vm/PrecompiledContracts.scala
- src/main/scala/io/iohk/ethereum/vm/ProgramContext.scala
- src/main/scala/io/iohk/ethereum/vm/ProgramResult.scala
- src/main/scala/io/iohk/ethereum/vm/ProgramState.scala
- src/test/scala/io/iohk/ethereum/Mocks.scala
- src/test/scala/io/iohk/ethereum/ledger/DeleteAccountsSpec.scala
- src/test/scala/io/iohk/ethereum/ledger/LedgerSpec.scala
- src/test/scala/io/iohk/ethereum/vm/CallOpcodesSpec.scala
We did not pass addresses already market to delete to CALLs, it allowed for multiple refunds for deleting the same address (see: CallSelfDestruct.sol - before this fix it results in 2x24000 refund).
Problematic tx: http://gastracker.io/tx/0x5688f0ea742a08e07349fe0fc585f0a4fbb1c311d67f2eff5f4a7461836ee9f3
>  EC-170: Fix gas refund for self destruct when using CALLs 

- src/test/scala/io/iohk/ethereum/validators/BlockHeaderValidatorSpec.scala
Our current test for the PoW validation in the `BlockHeaderValidator` tested the validation failing for `BlockHeader`s with random `nonce`s and `mixHash`es. As the current PoW validation is very simple (without using DAG), it could mark as valid blocks that aren't, which causes this test to randomly fail.
Replacing the test with random `nonce`s and `mixHash`es with one that tests only particular cases.
> Fix block header PoW validation test

- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
This fixes the issue when, after restarting during fast sync, some mpt nodes were "lost". Solution: we need to also save requested items in sync state (the ones that are not yet in db, but not in queues anymore).
> Fast sync download fix on restart	

- src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
Includes implementation of both `eth_blockNumber` and `eth_getTransactionByBlockHashAndIndex` methods. As `eth_getTransactionByBlockHashAndIndex` returns a transaction object, this PR is dependant on #179.
> RPC JSON: eth_blockNumber and eth_getTransactionByBlockHashAndIndex

- src/test/scala/io/iohk/ethereum/blockchain/sync/FastSyncBlockHeadersRequestHandlerSpec.scala
- src/test/scala/io/iohk/ethereum/transactions/PendingTransactionsManagerSpec.scala
This fixes (hopefully last) race condition that occurs in tests after switching to PeerMessageBus.
> Fix race condition in test

- src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
A custom ExecutionContext may be useful at some point, but it should be defined at class level, not per each single method in `EthService`. 
For now we stick with `global`. If we want to customise it in the future, the refactor will be easy - add class parameter, and provide it in `NodeBuilder`.
> remove per-method ExecutionContext in EthService

- src/main/scala/io/iohk/ethereum/jsonrpc/BlockResponse.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/EthJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
Includes `eth_getBlockByNumber` and `eth_getUncleByBlockNumberAndIndex` JSON RPC methods.
**Note:** Although according to https://github.com/ethereum/wiki/wiki/JSON-RPC#returns-26 `number`, `hash`, `nonce` and `logsBloom` should be `null` when the block tag is `Pending`, to keep the compatibility with geth the parameters selected as `null` were chosen as mentioned in https://github.com/ethereumproject/go-ethereum/blob/master/eth/api.go#L578.
> Added eth_getBlockByNumber and eth_getUncleByBlockNumberAndIndex

- src/main/scala/io/iohk/ethereum/jsonrpc/EthJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
`eth_estimateGas` implementation based on the same code as `eth_call`. As this is a the first approach, `EC-199` was created in order to do further investigation to check if we also need to do something like https://github.com/ethereum/go-ethereum/pull/3587 (which is implemented in parity too  https://github.com/paritytech/parity/blob/e6a31e7543e33b925908c8abc424060a28127290/ethcore/src/client/client.rs#L1045)
> [EC-198] eth_estimateGas

- src/main/scala/io/iohk/ethereum/network/PeerMessageBusActor.scala
- src/test/scala/io/iohk/ethereum/network/PeerMessageBusActorSpec.scala
Peer message bus implementation changed in order to:
- Don't send the notification twice if a subscription is made with two `MessageClassifier` with same message code, eg: `MessageClassifier(1,2,3)` and `MessageClassifier(2)` should only trigger once
- Allow users to Unsubscribe by code message code instead of the entire `MessageClassifier`
> PeerMessageBus refactor

- src/it/scala/io/iohk/ethereum/txExecTest/util/DumpChainApp.scala
- src/it/scala/io/iohk/ethereum/txExecTest/util/FixtureProvider.scala
- src/main/scala/io/iohk/ethereum/db/components/DataSourcesComponent.scala
- src/main/scala/io/iohk/ethereum/db/components/SharedEphemDataSources.scala
- src/main/scala/io/iohk/ethereum/db/components/SharedIodbDataSources.scala
- src/main/scala/io/iohk/ethereum/db/components/SharedLevelDBDataSources.scala
- src/main/scala/io/iohk/ethereum/db/components/Storages.scala
- src/main/scala/io/iohk/ethereum/db/components/StoragesComponent.scala
- src/main/scala/io/iohk/ethereum/db/storage/KeyValueStorage.scala
- src/main/scala/io/iohk/ethereum/db/storage/TransactionMappingStorage.scala
- src/main/scala/io/iohk/ethereum/domain/Blockchain.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/EthJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
- src/test/scala/io/iohk/ethereum/db/storage/TransactionMappingStorageSuite.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
Includes the implementation of the `eth_getTransactionByHash` JSON RPC method.
In order to do so, a `TransactionMappingStorage` was created which stores the mapping `TxHash -> (BlockHash, TxIndex)`.
> Implemented eth_getTransactionByHash

- src/main/scala/io/iohk/ethereum/jsonrpc/EthJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
When testing using Mist, the following requests are performed to `eth_estimateGas` endpoint and weren't supported by our implementation:
- Optional block parameter: `{"jsonrpc":"2.0","id":"6aed168f-91b6-485f-8ac1-86969de52e49","method":"eth_estimateGas","params":[{"from":"0xa797e6b221246a61141c7d04dfe2047e5b3ba620","to":"0x480d874B16C952efC6584F7A61bf3E8c38e39EDd","value":"0x578c6b4cf1583a8000","data":"0xaaaa","gas":"0x4c4b40"}]}`
- Allow data to be sent as "": `{"jsonrpc":"2.0","id":"6aed168f-91b6-485f-8ac1-86969de52e49","method":"eth_estimateGas","params":[{"from":"0xa797e6b221246a61141c7d04dfe2047e5b3ba620","to":"0x480d874B16C952efC6584F7A61bf3E8c38e39EDd","value":"0x578c6b4cf1583a8000","data":"","gas":"0x4c4b40"}, "latest"]}`
> Fixes in eth_estimateGas

- src/main/scala/io/iohk/ethereum/jsonrpc/http/JsonRpcHttpServer.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/http/JsonRpcHttpServerSpec.scala
While testing using Mist I've found that there are a lot batch requests being performed even if this is not stated it must be supported by clients in documentation. 
After implementing it, Mist stopped throwing errors and noticed some fixes. For example: accounts and balances are updated when added or mining.
- It's a basic implementation but seems to be working as parity does. 
- It doesn't check if two requests with same Id are sent in the same batch request (parity doesn't neither). Same case if the items within the batch array are the same
- Does not implement any limit / restriction on the amount of items a batch request might contain. Maybe we need to create a new task for this
> Basic Json Rpc batch requests support

- src/main/scala/io/iohk/ethereum/jsonrpc/EthJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
If the network consists of only our node, we are currently getting messages like -200 blocks left on Mist for synchronization, which is caused by our highest block estimation using only `NewBlocks` messages received from other peers, and this information is not available when our node is the only one.
Changed `eth_syncing` implementation to return that our node is not syncing when the highest estimated block (from peer information) is less or equal to the best block on our node.
> [EC-210] Fix negative blocks left (Mist)

- src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/FilterManager.scala
- src/main/scala/io/iohk/ethereum/mining/BlockGenerator.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/FilterManagerSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
- src/test/scala/io/iohk/ethereum/mining/BlockGeneratorSpec.scala
This PR implements the `pending` block filter which is used in several RPC methods as defined [here](https://github.com/ethereum/wiki/wiki/JSON-RPC#the-default-block-parameter)
- When block is queried and there is no pending, latest is returned as done in other clients
- Receipts are now saved in `BlockGenerator` as they are needed when having `pending` filter when calculating logs are needed
- Maybe `FilterManagerSpec` tests needs some more :heart: but I think this should be done in a separate task
> [EC-184] Pending block parameter

- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/jsonrpc/FilterManager.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/PersonalService.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
- src/main/scala/io/iohk/ethereum/transactions/PendingTransactionsManager.scala
- src/main/scala/io/iohk/ethereum/utils/Config.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/FilterManagerSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/PersonalServiceSpec.scala
- src/test/scala/io/iohk/ethereum/mining/BlockGeneratorSpec.scala
- src/test/scala/io/iohk/ethereum/ommers/OmmersPoolSpec.scala
- src/test/scala/io/iohk/ethereum/transactions/PendingTransactionsManagerSpec.scala
Currently, if 2 transactions (from the same sender) are sent without mining started (or if they arrive between the mining of 2 blocks), and the last one to arrive doesn't have a nonce field set, it will not included to the blockchain.
This happens when using both `eth_sendTransaction` and `personal_sendTransaction`, and it can be seen by using Mist as it doesn't set the nonce field when sending a tx. This can be reproduced by either:
* Starting the miner after the txs were sent.
* Increasing the mining difficulty to allow to send the txs so that they are attempted to be included in the same block.
The pending txs of the same sender are considered when setting the nonce of tx sent.
> [EC-223] Fix how default tx nonce is obtained when sending x_sendTransaction

- src/it/scala/io/iohk/ethereum/txExecTest/util/DumpChainApp.scala
- src/main/scala/io/iohk/ethereum/db/components/StoragesComponent.scala
- src/main/scala/io/iohk/ethereum/ledger/InMemorySimpleMapProxy.scala
- src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
- src/main/scala/io/iohk/ethereum/network/PeerActor.scala
- src/main/scala/io/iohk/ethereum/network/PeerEventBusActor.scala
- src/main/scala/io/iohk/ethereum/network/PeerManagerActor.scala
- src/main/scala/io/iohk/ethereum/network/p2p/Message.scala
- src/main/scala/io/iohk/ethereum/network/p2p/MessageDecoders.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
- src/main/scala/io/iohk/ethereum/validators/BlockHeaderValidator.scala
- src/main/scala/io/iohk/ethereum/validators/BlockValidator.scala
- src/main/scala/io/iohk/ethereum/vm/OpCode.scala
- src/test/scala/io/iohk/ethereum/ObjectGenerators.scala
- src/test/scala/io/iohk/ethereum/network/p2p/messages/MessagesSerializationSpec.scala
- src/test/scala/io/iohk/ethereum/network/p2p/messages/NewBlockSpec.scala
- src/test/scala/io/iohk/ethereum/rlp/RLPSuite.scala
Includes fixes to several `FIXME`s in the codebase. The remaining `FIXME`s were analyzed (with conclusions in task). The fixed `FIXME`s in this PR are:
- *BlockValidator: Can we avoid encoding ommers again? -> Removed FIXME*: This would require rethinking how messages are received from other peers, so as to leave the bytes of the messages cached, as Parity does. It doesn't seem worth the changes needed, as it would only improve the encoding of the ommers (for example, Geth doesn't implement this optimization), so the FIXME was removed.
- *InMemorySimpleMapProxy: We can cache retrieved values too -> Removed FIXME*: The optimization makes sense but it would require either: making the cache a var or returning a new InMemorySimpleMapProxy but it would unnecesary overcomplicate the interface. …
> [EC-238] Fixed FIXMEs in the codebase

- src/main/scala/io/iohk/ethereum/network/package.scala
- src/test/scala/io/iohk/ethereum/network/AsymmetricCipherKeyPairLoaderSpec.scala
In the scenario that the the node keys were already generated (in a previous execution of our client), when loaded and used to sign any message (using `ECDSASignature.sign(forSig, keyPair, None)`), a `null` exception happened.
This exception was caused by not restoring properly the node keys, as the public key was being used as the private key, which was fixed in this PR.
> [EC-245] Fixed how node key is restored

- src/main/scala/io/iohk/ethereum/vm/OpCode.scala
- src/test/scala/io/iohk/ethereum/vm/CreateOpcodeSpec.scala
- src/universal/conf/application.ini
There were 2 bugs:
- wrong value of gas was used as a base for code deposit gas check (value available in VM @ depth0, instead of the capped value in VM @ depth1 - init code)
- OOG was thrown, instead of consuming all gas passed to the VM @ depth1 (it's that VM that throws OOG, and in the parent VM it simply manifests as all gas used)
Additionally, JVM stack size was increased for the distribution.
> Fix bugs related to code deposit gas check within CREATE opcode

- src/it/scala/io/iohk/ethereum/txExecTest/util/DumpChainApp.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
- src/main/scala/io/iohk/ethereum/network/PeerActor.scala
- src/main/scala/io/iohk/ethereum/network/PeerManagerActor.scala
- src/main/scala/io/iohk/ethereum/network/discovery/PeerDiscoveryManager.scala
- src/main/scala/io/iohk/ethereum/network/rlpx/RLPxConnectionHandler.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
- src/main/scala/io/iohk/ethereum/utils/Config.scala
- src/main/scala/io/iohk/ethereum/vm/OpCode.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
- src/test/scala/io/iohk/ethereum/network/rlpx/RLPxConnectionHandlerSpec.scala
Includes fixes to several issues detected while running various static analysis tools.
The problems fixed were:
* Removed unused class constructors (`txPoolConfig` from `EthService` and `nodeKey` from `RLPxConnectionHandler`).
* Removed unused parameter when pattern matching on `LogOp`.
* Removed empty interpolated string (`s"..."`).
* Removed unused imports.
> Static analysis tools fixes

- src/main/scala/io/iohk/ethereum/network/PeerActor.scala
- src/main/scala/io/iohk/ethereum/network/rlpx/RLPxConnectionHandler.scala
- src/test/scala/io/iohk/ethereum/network/rlpx/RLPxConnectionHandlerSpec.scala
In case incoming connections are enabled (having `server-address.interface="0.0.0.0"`), when a client is restarted with a new node key, many incoming connection attempts were received that caused both an invalid MAC and increasing the number of connected nodes well beyond the limit (ex: `Discovered 0 nodes, connected to 94/45. Trying to connect to 0 more nodes.`).
This PR includes a fix to the huge number of connected nodes, which was caused by the [exception restarting the RLPxConnectionHandler](http://doc.akka.io/docs/akka/current/scala/fault-tolerance.html#default-supervisor-strategy), as no handling of this exception was done. This was fixed by closing the connection in case any exception happened during the MAC check.
**Note:** In the depicted scenario the invalid MAC was caused by …
> Handle invalid MAC exception on RLPxConnectionHandler

- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSyncNodesRequestHandler.scala
- src/main/scala/io/iohk/ethereum/utils/Config.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/SyncControllerSpec.scala
this PR is to not blacklist peers which are not responding with mpt nodes, instead we mark them as blockchain only, this PR also changes order in which we schedule fast sync element to get mpt as fast as possible
> [EC-256] Regression test for fast sync

- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
This PR handle case when we have requested block bodies by hashes for block headers that are not in our DB, this may happen because of killing client while persisting data
> Missing block headers

- src/main/scala/io/iohk/ethereum/jsonrpc/PersonalService.scala
- src/main/scala/io/iohk/ethereum/keystore/KeyStore.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/PersonalServiceSpec.scala
- src/test/scala/io/iohk/ethereum/keystore/KeyStoreImplSpec.scala
When using `personal_importRawKey` to import an already imported account, it succeeds, which causes `personal_listAccounts` to list an account twice. In contrast, Geth returns an error message (`"account already exists"`) when an already imported account is imported again.
Check whether an account was already saved to the `KeyStore` before saving a new one.
> [EC-270] Fixed personal_importRawKey on duplicated import

- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/NetService.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
- src/main/scala/io/iohk/ethereum/utils/Config.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
When using the JSON RPC method `net_version` on the Morden testnet the value `"1"` was returned, while both the [specification](https://github.com/ethereum/wiki/wiki/JSON-RPC#net_version) and Geth and Parity clients return `"2"`.
Fixed `net_version` to use `network-id` configuration instead of `protocol-version` (which never changed from `"1"`).
The value of `protocol-version` was also fixed according to [specification](https://github.com/ethereum/wiki/wiki/Ethereum-Wire-Protocol#ethereum-sub-protocol) and it was added to be used on `eth_protocolVersion`
> [EC-269] Fixed net_version on Morden

- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/SyncBlockHeadersRequestHandler.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/FastSyncBlockHeadersRequestHandlerSpec.scala
This PR is to ask for block bodies and receipts only if we are sure that block header was inserted into DB
This also removes block and receipts scheduling from `SyncBlockHeadersRequestHandler` which should be handled by `FastSync`
> [EC-278] Missing block headers when client is restarted

- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/SyncController.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
- src/main/scala/io/iohk/ethereum/utils/Config.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/SyncControllerSpec.scala
In the scenario that:
* The client is started with fast sync enabled but it is canceled it before it completes
* The client is restarted with regular sync enabled.
currently it resulted in the client throwing the exception `Node not found, trie is inconsistent`.
The exception is caused by trying to retrieve the MPT for the `BestBlockNumber` saved during fast sync, for which no MPT node is stored.
This was fixed by continuing with fast sync and logging this, even though regular sync was selected.
> [EC-167] Fix error while running regular sync without all MPT nodes

- src/main/scala/io/iohk/ethereum/db/storage/BlockBodiesStorage.scala
- src/main/scala/io/iohk/ethereum/domain/SignedTransaction.scala
- src/main/scala/io/iohk/ethereum/network/p2p/messages/PV62.scala
Based on the reported issue "client seems to get slower (in terms of block processing) around block 50k" we started to run some tests and benchmarks and reached to the conclusion there is an issue when validating blocks before inserting them while fast sync and when executing them during regular sync. To be more precise:
1. When receiving a block during regular & fast sync we need to, amongst other checks, to validate ommers (if present). Thats done in `io.iohk.ethereum.validators.OmmersValidatorImpl#validate`
2. One of those checks is to validate that an ommer hasn't been used on previous blocks as ommer [YP section 11.1 eq 143, 144 and 145](http://gavwood.com/paper.pdf)
3. To do perform (2) we were retrieving up to 6 parent block bodies from db. When doing so we were deserializing both …
> [EC-280] Find and fix performance bottleneck in peer download

- src/main/scala/io/iohk/ethereum/blockchain/sync/BlockBroadcast.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/RegularSync.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/BlockBroadcastSpec.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/SyncControllerSpec.scala
Modifies the block propagation algorithm from sending `NewBlock` messages to all peers, to sending `NewBlockHashes` messages to all peers but sending `NewBlock` messages to only a randomly selected `sqrt(|peers|)` as both Parity and Geth propagate blocks that way.
> [EC-87] BlockBroadcast propagation algorithm

- src/it/scala/io/iohk/ethereum/txExecTest/ForksTest.scala
- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/utils/Config.scala
- src/main/scala/io/iohk/ethereum/validators/BlockHeaderValidator.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/PersonalServiceSpec.scala
- src/test/scala/io/iohk/ethereum/mining/BlockGeneratorSpec.scala
- src/test/scala/io/iohk/ethereum/network/handshaker/EtcHandshakerSpec.scala
- src/test/scala/io/iohk/ethereum/validators/BlockHeaderValidatorSpec.scala
- src/universal/conf/blockchain.conf
Validating that block header gas limit is lower than 2**63-1
> [EC-302] Adding maximum gasLimit validation

- build.sbt
While running, sometimes leveldb was throwing `Could not open table XXXX`
This PR includes our forked leveldb dependency.
- Leveldb issue explanation: https://github.com/dain/leveldb/issues/78 
- Leveldb change: https://github.com/input-output-hk/leveldb/commit/e569b84b069d1d4278bf35c86d0be54badbd90b4
> EC-265 Spurious database error

- src/universal/conf/ropsten.conf
This PR adds `eip161-block-number` config taken from https://raw.githubusercontent.com/paritytech/parity/master/ethcore/res/ethereum/ropsten.json
> Add EIP161 block number config to ropsten.conf

- src/ets/scala/io/iohk/ethereum/ets/blockchain/BlockchainSuite.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/RegularSync.scala
- src/main/scala/io/iohk/ethereum/domain/Block.scala
- src/main/scala/io/iohk/ethereum/domain/BlockHeader.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
- src/main/scala/io/iohk/ethereum/ledger/BlockQueue.scala
- src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
- src/main/scala/io/iohk/ethereum/mining/BlockGenerator.scala
- src/main/scala/io/iohk/ethereum/mining/Miner.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
- src/main/scala/io/iohk/ethereum/validators/BlockHeaderValidator.scala
- src/main/scala/io/iohk/ethereum/validators/OmmersValidator.scala
- src/test/scala/io/iohk/ethereum/Mocks.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
- src/test/scala/io/iohk/ethereum/ledger/BlockImportSpec.scala
- src/test/scala/io/iohk/ethereum/ledger/BlockQueueSpec.scala
- src/test/scala/io/iohk/ethereum/mining/BlockGeneratorSpec.scala
- src/test/scala/io/iohk/ethereum/mining/MinerSpec.scala
- src/test/scala/io/iohk/ethereum/validators/OmmersValidatorSpec.scala
[EC-319](https://iohk.myjetbrains.com/youtrack/issue/EC-319)
The easiest approach was taken which is to disallow orphaned blocks. The ranged difficulty validation proves to be a bit more complex when dealing with forks. We may still do it in a follow-up task (configurable with a switch), though there's probably not a lot to be gained for overall syncing speed.
However, the code as currently is may be somewhat over-engineered in the area of `Ledger` / `BlockQueue` in that from the start it was meant to handle orphaned blocks.
There might be a third alternative: have a size limit on the queue, and delay validation until the actual execution. For that to work, however, queued blocks need to be associated with the peers they were received from. That would require refactoring the `BlockQueue` …
> [EC-319] pre-import validation / disallow orphaned blocks

- src/main/scala/io/iohk/ethereum/mpt/MerklePatriciaTrie.scala
- src/test/scala/io/iohk/ethereum/mpt/MerklePatriciaTrieSuite.scala
This PR includes two fixes:
- When Root node is not found, a different error message is thrown
- There was a bad comparison between an Array[Byte] and a ByteString
> MPT Fixes: Better error when root node was not found & wrong comparison

- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/jsonrpc/server/JsonRpcHttpsServer.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/server/JsonRpcServer.scala
- src/main/scala/io/iohk/ethereum/utils/Config.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/server/JsonRpcServerSpec.scala
- src/universal/conf/network.conf
Enables configuring the type of certificate keystore being used.
This allows recreating a certificate keystore from a certificate and key files (using `openssl pkcs12 -export ...` command), which is needed for obtaining a keystore for the Mantis client based on the `server.crt` and `server.key` from [Daedalus](https://github.com/input-output-hk/daedalus/tree/master/tls).
> Enable configuring certificate keystore type

- src/main/scala/io/iohk/ethereum/jsonrpc/server/JsonRpcHttpsServer.scala
An invalid `isDirectory` check was being done on the certificate keystore, while it is not a directory but a file, so the check was replaced with `isFile`.
> Replaced invalid isDirectory check for certificate keystores

- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/db/storage/ReferenceCountNodeStorage.scala
- src/main/scala/io/iohk/ethereum/db/storage/encoding/package.scala
- src/test/scala/io/iohk/ethereum/db/storage/ReferenceCountNodeStorageSpec.scala
- src/universal/conf/storage.conf
After latest pruning algorithm change in order to handle chain reorgs made in https://github.com/input-output-hk/mantis/pull/325, two issues were introduced:
- Mantis Fast Sync Server broken after new pruning implementation
- Miner reports and error if it requests work while applying a block
Latest implementation only keeps latest version of MPT nodes in db. Deleted ones are moved to a stash area where they can be taken in case of a rollback but cannot be accessed in order to serve it to other services (miner, fast sync host actor).
The following change delays MPT node removal from DB until it's pruned. In order to do so, it checks if it's no longer needed looking for:
- Zero references in the latest version
- It wasn't referenced by any other change in later blocks
> [EC-344] Pruning should keep some old MPT Nodes

- src/main/scala/io/iohk/ethereum/mining/Miner.scala
- src/test/scala/io/iohk/ethereum/mining/MinerSpec.scala
It could happen that our miner generated a nonce that was longer (or shorter) than required 8 bytes. Mantis accepted such blocks just fine, but Geth was rejecting them. Actually, what do you think about also validating it (nonce length) as a part of block validation?
> Fix nonce in miner

- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/blockchain/sync/RegularSync.scala
- src/main/scala/io/iohk/ethereum/utils/Config.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/RegularSyncSpec.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/SyncControllerSpec.scala
Branch resolution has been simplified by making a single request (of configurable size) for additional headers. Therefore no additional constraints for branch length are required.
This has been tested by revoking the fix made in #352 and forcing the issue to occur. After re-applying the said fix, syncing resumed immediately - previously it wouldn't have happened unless a peer chose to ignore our request for 200 headers and responded instead with something between 1 and 13 headers (which probably would have happened eventually).
> [EC-358] fix branch resolution depth

- src/main/scala/io/iohk/ethereum/network/handshaker/EtcNodeStatusExchangeState.scala
- src/test/scala/io/iohk/ethereum/network/handshaker/EtcHandshakerSpec.scala
- src/test/scala/io/iohk/ethereum/network/p2p/PeerActorSpec.scala
Adds validation of the `genesisHash` and `networkId` from the status message received from remote peers. In case an invalid status is received the peer is disconnected with a `DisconnectRequested` reason, as done in Parity.
> [EC-377] Added peer status validation

- src/main/scala/io/iohk/ethereum/consensus/Ethash.scala
- src/main/scala/io/iohk/ethereum/crypto/package.scala
- src/main/scala/io/iohk/ethereum/utils/ByteUtils.scala
Main improvements by:
1. rewriting foreach as while loops, and avoiding allocation of `Range` object ( `scalac` compiler should do this under the hood, but as it seems it fails sometimes)
2. Avoiding Allocation new Keccak512 engine during each hash computation as it is quite expensive. And taking digest always reset engine to starting state. 
3. optimising array translations between byte and int array.  changing `scala` constructs `map` and `flatMaps` to operations on`ByteFuffers`.  
As it stands  current bottleneck is point `3`, but as I rewritten those to manually manipulating bytes on pre-allocated arrays,  point of contention just moved to https://github.com/input-output-hk/mantis/pull/377/files#diff-0dafe97cd157b1f1432980a711be1ebdR196, and there was only little speedup (1 - 2%) so i …
> [EC-395] Optimisation of ethash algorithm

- src/ets/scala/io/iohk/ethereum/ets/blockchain/BlockchainTestConfig.scala
- src/it/scala/io/iohk/ethereum/SimulateTransactionTest/SimulateTransactionTest.scala
- src/it/scala/io/iohk/ethereum/txExecTest/ECIP1017Test.scala
- src/it/scala/io/iohk/ethereum/txExecTest/ForksTest.scala
- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/domain/DifficultyCalculator.scala
- src/main/scala/io/iohk/ethereum/utils/Config.scala
- src/snappy/resources/example.conf
- src/test/scala/io/iohk/ethereum/jsonrpc/PersonalServiceSpec.scala
- src/test/scala/io/iohk/ethereum/ledger/ContractCreationSpec.scala
- src/test/scala/io/iohk/ethereum/ledger/LedgerSpec.scala
- src/test/scala/io/iohk/ethereum/mining/BlockGeneratorSpec.scala
- src/test/scala/io/iohk/ethereum/network/handshaker/EtcHandshakerSpec.scala
- src/test/scala/io/iohk/ethereum/validators/BlockHeaderValidatorSpec.scala
- src/universal/conf/blockchain.conf
- src/universal/conf/ethereumHF.conf
- src/universal/conf/morden.conf
- src/universal/conf/ropsten.conf
Docs: https://github.com/ethereumproject/ECIPs/blob/master/ECIPs/ECIP-1041.md
Afaik it only affects classic and morden.
> [EC-484] Implement ecip1041

- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/network/PeerActor.scala
- src/main/scala/io/iohk/ethereum/network/PeerManagerActor.scala
- src/main/scala/io/iohk/ethereum/network/discovery/Node.scala
- src/main/scala/io/iohk/ethereum/network/discovery/PeerDiscoveryManager.scala
- src/main/scala/io/iohk/ethereum/utils/ValidationUtils.scala
- src/test/resources/application.conf
- src/test/scala/io/iohk/ethereum/network/NodeParserSpec.scala
- src/test/scala/io/iohk/ethereum/network/discovery/PeerDiscoveryManagerSpec.scala
- src/test/scala/io/iohk/ethereum/network/p2p/PeerActorSpec.scala
Now each peer can have udp and tcp ports specified separatly.
The logic of discovery needed to be changed, as the only way to get udp and tcp ports separately is from `neighbours` message.
Also, there are some minor changes that should help with bug that some times our discovery is stuck at some nodes count and wont progress because it missed one or more good peers. (it can still happen but it is rarer from my several runs)
> [EC-423] Bug/hande tcp udp ports

- src/main/scala/io/iohk/ethereum/db/dataSource/DataSource.scala
- src/main/scala/io/iohk/ethereum/db/dataSource/EphemDataSource.scala
- src/main/scala/io/iohk/ethereum/db/dataSource/IodbDataSource.scala
- src/main/scala/io/iohk/ethereum/db/dataSource/LevelDBDataSource.scala
- src/main/scala/io/iohk/ethereum/db/storage/NodeStorage.scala
- src/main/scala/io/iohk/ethereum/db/storage/ReferenceCountNodeStorage.scala
1. Replace builidng list of nodes to delete in pruning
from append to seq to prepend to list.
2. During serialization of nodes use the fact that
value is already array[Byte] and key is bytestring
As for potential improvements, during sync from master locally:
Baseline - 55min
Improved - 45min
Baseline:
```
22:06:15 [i.i.e.blockchain.sync.RegularSync] - Block: 756826. Peers: 1 (0 blacklisted)
22:16:20 [i.i.e.blockchain.sync.RegularSync] - Block: 762330. Peers: 1 (0 blacklisted)
10min - 5504
22:36:17 [i.i.e.blockchain.sync.RegularSync] - Block: 776538. Peers: 1 (0 blacklisted)
30 min - 19712 blocks
```
Improved:
```
11:30:18 [i.i.e.blockchain.sync.RegularSync] - Block: 756826. Peers: 1 (0 blacklisted)
11:40:19 [i.i.e.blockchain.sync.RegularSync] - Block: 762714. Peers: 1 (0 blacklisted) …
```
> Fix performance bottle neck in storages

- .circleci/config.yml
This will run the full ETS for `phase/iele_testnet` branch, twice a week - every Wed and Sat at 4 a.m. UTC.
Though `phase/release1_1` is also listed, the current settings for it shouldn't be affected, unless this gets merged to that branch. At least that's my understanding based on some experiments. The documentation is vague on how exactly the [branch filters](https://circleci.com/docs/2.0/workflows/#branch-level-job-execution) work with regard to [scheduled workflows](https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow).
It may be a good idea to try something like:
```
filters:
branches:
only:
- /^phase\/.*/
```
in the future, but for now I wanted to be safe and explicit.
The workflow was tested by configuring it to this branch (`feature/scheduleEtsForIeleBranch`) scheduled …
> [CGKIELE-118] schedule full ETS for IELE branch

- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/SyncControllerSpec.scala
Handling of two cases:
1. Handle the case when we are constantly receiving 0 headers from one peer. As we are choosing our blockheader peer as first free peer, it could happen that we will ask headers from a peer which constantly send us 0, it can greatly impair our syncing.
2. Handle case when peer will send us header from the future e.g our best block is `10` and we requested blocks from `11` to `20`, and peer sends us block/blocks which start from block `5000`.  Of course, this block will fail validation, but it will change our best block to `5000 - N - 1`. Currently `N` is equal to `2048` so our best block number would be `2951` which is obviously incorrect.
We are always asking our peers for headers from `bestBlock + 1`, so if we receive some headers from beyond that we can assume …
> [EC-522] Make fastSync more resisilent to failures

- .circleci/config.yml
(cheery picked from `phase/iele` branch
> fix: update docker image version for scheduled ETS

- src/universal/conf/ethereumHF.conf
basicly concept of eras is only relevat to ethereum classic, and on ethereum chain we want to be in 0 era. Current highest block on etherum chain is `5897827` so with old config we would end up in era 1, and block would fail to validate.
Setting it to 50,000,000 will be enough for next ~15 years with current block generation speed.
> Increase era duration for ethereum to 50milion blocks

- src/main/scala/io/iohk/ethereum/healthcheck/Healthcheck.scala
- src/main/scala/io/iohk/ethereum/healthcheck/HealthcheckResponse.scala
- src/main/scala/io/iohk/ethereum/healthcheck/HealthcheckResult.scala
- src/main/scala/io/iohk/ethereum/healthcheck/HealthcheckStatus.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerMetrics.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcHealthcheck.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpServer.scala
We serve the `/healthcheck` endpoint by a small library that
supports the definition, execution and interpretation of
health checks.
We also introduce a metric that keeps track of erroneous
health checks, `json.rpc.healthcheck.error.counter`, which
is routed normally through the metrics export pipeline.
Ref CGKIELE-425
From the command line, with `curl`:
```
$ curl -i TESTNET_URL/healthcheck
```
where we should replace `TESTNET_URL` with an actual testnet URL, port included. 
If at least one of the health checks returns error, then the endpoint responds with an error `500`.
```
HTTP/1.1 500 Internal Server Error
Server: akka-http/10.0.6
Date: Fri, 06 Jul 2018 08:46:58 GMT
Content-Type: application/json
Content-Length: 394
{
"checks":[
{
"description":"peerCount",
"status":"OK"
},
{ …
```
> Health checks

- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/consensus/atomixraft/AtomixRaftConsensus.scala
- src/main/scala/io/iohk/ethereum/consensus/atomixraft/AtomixRaftForger.scala
- src/universal/conf/consensus.conf
`mining-enabled` has been silently ignored by the code in the case
of `atomix-raft` consensus. The code just assumes a value of
`true`. The assumption is correct regarding the current design,
since all nodes participate in the Raft consensus, but we need
more operational flexibility. In particular, we may need to
temporarily disable forging until a (recovering) node completely
syncs the blockchain and re-enable it afterwards, thus resuming
normal operation.
The current patch inspects the value of `mining-enabled` and acts
accordingly.
Ref CGKIELE-318
> Selective forging

- .gitignore
- build.sbt
- project/plugins.sbt
- src/main/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpServer.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/StdNode.scala
- src/main/scala/io/iohk/ethereum/utils/JsonUtils.scala
From a running node, it is now possible to know exactly which
commit the code is based on, along with some other metadata.
This _buildinfo_ is exported via the logging subsystem when the
node boots, and it is also available under the `/buildinfo`
HTTP endpoint (using the HTTP mode of JSON/RPC).
Ref CGKIELE-463
> Export build-related info

- build.sbt
- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/blockchain/data/GenesisDataLoader.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/RegularSync.scala
- src/main/scala/io/iohk/ethereum/consensus/atomixraft/AtomixRaftForger.scala
- src/main/scala/io/iohk/ethereum/domain/BlockHeader.scala
- src/main/scala/io/iohk/ethereum/network/handshaker/EtcHelloExchangeState.scala
- src/main/scala/io/iohk/ethereum/network/handshaker/EtcNodeStatusExchangeState.scala
- src/main/scala/io/iohk/ethereum/network/p2p/Message.scala
- src/main/scala/io/iohk/ethereum/network/p2p/messages/CommonMessages.scala
- src/main/scala/io/iohk/ethereum/network/p2p/messages/PV61.scala
- src/main/scala/io/iohk/ethereum/network/p2p/messages/PV62.scala
- src/main/scala/io/iohk/ethereum/network/p2p/messages/PV63.scala
- src/main/scala/io/iohk/ethereum/network/p2p/messages/WireProtocol.scala
- src/main/scala/io/iohk/ethereum/network/peer.scala
- src/main/scala/io/iohk/ethereum/utils/Config.scala
- src/main/scala/io/iohk/ethereum/utils/Riemann.scala
- verify.sbt
* events are batched up to be more efficient
* batches are sent once the batch is full and periodically
* events are also buffered
* backpressure causes events to overflow into stdout (as JSON)
* connection failure causes overflow to stdout JSON
* if you do not add riemann configuration then this simply
provides a JSON stdout logger
With this you should avoid calls to `log.debug` `log.info` etc and send Riemann events instead. Logging should be reserved for detailed debugging/tracing only.
If this is merged then pretty much every `log.{info,debug,error}` can be migrated to a riemann service without really affecting the functionality.
> Riemann poc

- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
simple change to make total node count independent from  request, which led to highly volatile outpu
> [EC-359] Make total nodes count independent from requests

- src/main/scala/io/iohk/ethereum/vm/OpCode.scala
- src/test/scala/io/iohk/ethereum/vm/CreateOpcodeSpec.scala
- src/test/scala/io/iohk/ethereum/vm/Generators.scala
- src/test/scala/io/iohk/ethereum/vm/OpCodeFunSpec.scala
According to yellow paper returndata buffer needs to be cleared after `SELFDESTRUCT`
> Clear buffer after self destruct

- src/main/scala/io/iohk/ethereum/extvm/World.scala
- src/main/scala/io/iohk/ethereum/ledger/BlockPreparator.scala
- src/main/scala/io/iohk/ethereum/ledger/InMemoryWorldStateProxy.scala
- src/main/scala/io/iohk/ethereum/vm/OpCode.scala
- src/main/scala/io/iohk/ethereum/vm/WorldStateProxy.scala
- src/test/scala/io/iohk/ethereum/ledger/DeleteTouchedAccountsSpec.scala
- src/test/scala/io/iohk/ethereum/ledger/InMemoryWorldStateProxySpec.scala
- src/test/scala/io/iohk/ethereum/vm/CallOpcodesSpecPostEip161.scala
- src/test/scala/io/iohk/ethereum/vm/MockWorldState.scala
Touched account handling updtaed to clarified spec: 
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-161.md - `The specification was amended to clarify that empty account deletions are reverted when the state is reverted.`
Also taking into account bug in parity and geth.
> Fix touched account handling

- src/main/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpServer.scala
We've seen responses with 400 status not being CORS-enabled.
This patch should fix it by returning proper CORS headers.
Note that we already use some custom rejection (in akka terminology)
handler, which we leave as is.
See `myRejectionHandler` in `JsonRpcHttpServer`.
Tested locally.
Ref CGKIELE-570
> Send CORS headers even on error

- README.md
- src/main/scala/io/iohk/ethereum/blockchain/data/GenesisDataLoader.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSyncStateStorageActor.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/RegularSync.scala
- src/main/scala/io/iohk/ethereum/consensus/atomixraft/AtomixRaftConsensus.scala
- src/main/scala/io/iohk/ethereum/consensus/atomixraft/AtomixRaftForger.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
- src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
- src/main/scala/io/iohk/ethereum/network/KnownNodesManager.scala
- src/main/scala/io/iohk/ethereum/network/PeerManagerActor.scala
- src/main/scala/io/iohk/ethereum/network/ServerActor.scala
- src/main/scala/io/iohk/ethereum/network/handshaker/EtcForkBlockExchangeState.scala
- src/main/scala/io/iohk/ethereum/network/handshaker/EtcHelloExchangeState.scala
- src/main/scala/io/iohk/ethereum/network/handshaker/EtcNodeStatusExchangeState.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/StdNode.scala
- src/main/scala/io/iohk/ethereum/utils/Config.scala
- src/main/scala/io/iohk/ethereum/utils/Riemann.scala
- src/main/scala/io/iohk/ethereum/utils/Scheduler.scala
- src/main/scala/io/iohk/ethereum/utils/events/EventSupport.scala
- src/main/scala/io/iohk/ethereum/utils/events/package.scala
There are now quite a few Riemann events in place of logging, this means after this PR you really would be better off running a simple Riemann server (`docker run --rm -p 5555:5555 -p 5556:5556 riemannio/riemann`) and using `rcl` with `jq`. 
Installing `rcl` requires either nix (it's built in our Hydra) or stack at the moment as I don't have any need to distribute it anywhere else.
This is basically structured logging from a developer point of view and my intention would be to remove all `log.*` calls except for a few odd `log.debug` calls perhaps and ofc the logs that other libraries produce such as akka and netty.
> Replace some logging with Riemann events

- src/main/scala/io/iohk/ethereum/blockchain/sync/BlacklistSupport.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/RegularSync.scala
- src/main/scala/io/iohk/ethereum/consensus/validators/BlockHeaderValidator.scala
- src/main/scala/io/iohk/ethereum/consensus/validators/BlockHeaderValidatorSkeleton.scala
- src/main/scala/io/iohk/ethereum/domain/BlockHeader.scala
- src/main/scala/io/iohk/ethereum/domain/SignedTransaction.scala
- src/main/scala/io/iohk/ethereum/ledger/BlockPreparator.scala
- src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
- src/main/scala/io/iohk/ethereum/metrics/Metrics.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/RegularSyncSpec.scala
- src/test/scala/io/iohk/ethereum/consensus/validators/BlockHeaderValidatorSpec.scala
- src/test/scala/io/iohk/ethereum/ledger/BlockImportSpec.scala
to (usually) INFO. The idea is to avoid the verbosity of DEBUG
and yet be able to understand what is going on, especially
regarding the blockchain progress (or lack thereof). The
usefulness and effectiveness of this patch has been verified
while debugging a real case in production.
Also:
- augment `HeaderGasLimitError` with context to aid debugging
- provide two sub-cases for `InvalidBranch`, thus making the
precise error clearer
- augment `Block`'s `idTag` with extra info to aid debugging
- use `block.idTag` as the default way to identify a block
when logging
Ref CGKIELE-397
> Promote logs of business impact from DEBUG

- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/jsonrpc/server/http/BasicJsonRpcHttpServer.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpServer.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpServerMetrics.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpsServer.scala
- src/main/scala/io/iohk/ethereum/metrics/Metrics.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpServerSpec.scala
This avoids observed non-deterministic behavior that bubbles up as
request parsing errors (probably caused by consuming a stream
more than once).
Ref CGKIELE-570
> jsonrpc: Make request body strict

- src/main/scala/io/iohk/ethereum/blockchain/sync/RegularSync.scala
- src/main/scala/io/iohk/ethereum/domain/SignedTransaction.scala
In regular sync as soon as blocks received, calculate and cache senders for each tx. 
Performace gains during 3h of sync from master node:
`baseline - 766976 blocks synced`
`backgroundSenders - 816001 blocks synced`
> Calculate and cache senders in background

- src/benchmark/scala/io/iohk/ethereum/mpt/MerklePatriciaTreeSpeedSpec.scala
- src/it/scala/io/iohk/ethereum/txExecTest/util/DumpChainActor.scala
- src/it/scala/io/iohk/ethereum/txExecTest/util/FixtureProvider.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
- src/main/scala/io/iohk/ethereum/mpt/HexPrefix.scala
- src/main/scala/io/iohk/ethereum/mpt/MerklePatriciaTrie.scala
- src/main/scala/io/iohk/ethereum/mpt/Node.scala
- src/rpcTest/scala/io/iohk/ethereum/rpcTest/RpcApiTests.scala
- src/test/scala/io/iohk/ethereum/ObjectGenerators.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/BlockchainHostActorSpec.scala
- src/test/scala/io/iohk/ethereum/network/p2p/messages/NodeDataSpec.scala
1st batch of improvements to mpt trie, changes:
Reduce unnecessery allocations of wrappers (`Option`, `Either`).
Use Arrays and while loops where possible.
changes to `MptNode` encoding enables further refactorings and possible performance gains but i did not want to make this pr to big. (extending `MptNode` required some additional exception throws in pattern matching clauses to satisfy compiler)
Performance gains (30min sync ):
Baseline - 288577blocks
Improved - 301057blocks
~5%
> Improve Mpt trie performance

- src/main/scala/io/iohk/ethereum/vm/OpCode.scala
- src/test/scala/io/iohk/ethereum/vm/ShiftingOpCodeSpec.scala
According to specs:
`the result is 0 if arg2 is non-negative`
> fix sar instruction

- src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockImporter.scala
- src/main/scala/io/iohk/ethereum/vm/Memory.scala
1. Add caluclating senders in background - It was used earlier in regular sync so this is nothing new
2. Fix performance of store operation- 
As it seems `MSTORE` is one of most frequent used opcodes in eth, and our courrent implementation clogs on it when synchronising on top of the chain.
[https://ibb.co/jJ7wvLv](url) - almost 5/6 of vm time spent in store.
This pr introduces optimised implementation.
- Microbenchmarks (which i have written on the side and are not 100% reliable) shows 4x optimization with that implementation
- block processing speed as i am currently running eth increased from `50blocks / 5min` to `50blocks/2min`
- visual vm shows that now only 1/4 vm time is spent in `MSTORE`
> Add cacluclatin senders in background. Fix mem performance

- src/test/scala/io/iohk/ethereum/vm/OpCodeFunSpec.scala
test was failing when `codehash` was hash of empty code, the account was empty then and zero was pushed onto stack
> fix extcodehash test fail

- src/main/scala/io/iohk/ethereum/extvm/VMServer.scala
- src/main/scala/io/iohk/ethereum/vm/BlockchainConfigForEvm.scala
- src/main/scala/io/iohk/ethereum/vm/EvmConfig.scala
- src/main/scala/io/iohk/ethereum/vm/OpCode.scala
- src/test/scala/io/iohk/ethereum/extvm/VMClientSpec.scala
- src/test/scala/io/iohk/ethereum/vm/Fixtures.scala
- src/test/scala/io/iohk/ethereum/vm/OpCodeFunSpec.scala
- src/test/scala/io/iohk/ethereum/vm/VMSpec.scala
> [ETCM-19] chainId opcode

- src/main/scala/io/iohk/ethereum/vm/EvmConfig.scala
- src/main/scala/io/iohk/ethereum/vm/OpCode.scala
- src/test/scala/io/iohk/ethereum/vm/Generators.scala
- src/test/scala/io/iohk/ethereum/vm/OpCodeFunSpec.scala
- src/test/scala/io/iohk/ethereum/vm/OpCodeGasSpec.scala
https://eips.ethereum.org/EIPS/eip-1884
> [ETCM-20] Repricing for trie-size-dependent opcodes

- src/main/scala/io/iohk/ethereum/vm/EvmConfig.scala
- src/test/scala/io/iohk/ethereum/ledger/StxLedgerSpec.scala
https://eips.ethereum.org/EIPS/eip-2028
> [ETCM-21] EIP-2028: Transaction data gas cost reduction

- src/main/scala/io/iohk/ethereum/vm/OpCode.scala
- src/test/scala/io/iohk/ethereum/vm/Fixtures.scala
- src/test/scala/io/iohk/ethereum/vm/Generators.scala
- src/test/scala/io/iohk/ethereum/vm/OpCodeGasSpec.scala
- src/test/scala/io/iohk/ethereum/vm/PrecompiledContractsSpec.scala
- src/test/scala/io/iohk/ethereum/vm/SSTOREOpCodeGasPostConstantinopleSpec.scala
https://eips.ethereum.org/EIPS/eip-2200
> Etcm 22 structured definitions for net gas metering

- src/ets/scala/io/iohk/ethereum/ets/blockchain/BlockchainTestConfig.scala
- src/it/scala/io/iohk/ethereum/txExecTest/ECIP1017Test.scala
- src/it/scala/io/iohk/ethereum/txExecTest/ForksTest.scala
- src/main/resources/chains/base.conf
- src/main/resources/chains/eth.conf
- src/main/scala/io/iohk/ethereum/extvm/VMServer.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/TestService.scala
- src/main/scala/io/iohk/ethereum/utils/Config.scala
- src/main/scala/io/iohk/ethereum/vm/BlockchainConfigForEvm.scala
- src/main/scala/io/iohk/ethereum/vm/EvmConfig.scala
- src/test/scala/io/iohk/ethereum/consensus/BlockGeneratorSpec.scala
- src/test/scala/io/iohk/ethereum/consensus/validators/BlockHeaderValidatorSpec.scala
- src/test/scala/io/iohk/ethereum/extvm/VMClientSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/PersonalServiceSpec.scala
- src/test/scala/io/iohk/ethereum/ledger/LedgerTestSetup.scala
- src/test/scala/io/iohk/ethereum/ledger/StxLedgerSpec.scala
- src/test/scala/io/iohk/ethereum/network/handshaker/EtcHandshakerSpec.scala
- src/test/scala/io/iohk/ethereum/vm/Fixtures.scala
- src/test/scala/io/iohk/ethereum/vm/VMSpec.scala
> [ETCM-41] Add Istanbul fork configuration

- src/main/resources/chains/private.conf
- src/universal/conf/private-testnet.conf
Initial config for the private testnet:
1. Node syncs using regular sync
2. Mining is enabled
3. Phoenix fork config will be a base for chain
4. Disabled features:
- pruning
- discovery
- blacklisting
> [CHORE] Testnet config

- .scalafmt.conf
- build.sbt
- insomnia_workspace.json
- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/consensus/Consensus.scala
- src/main/scala/io/iohk/ethereum/consensus/ConsensusBuilder.scala
- src/main/scala/io/iohk/ethereum/consensus/Protocol.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/EthashBlockCreator.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/EthashConsensus.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/EthashMiner.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/MinerProtocol.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/MinerUtils.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/MockedMiner.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/TransactionPicker.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/QAJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/QAService.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
- src/main/scala/io/iohk/ethereum/testmode/TestmodeConsensus.scala
- src/test/resources/application.conf
- src/test/scala/io/iohk/ethereum/ByteGenerators.scala
- src/test/scala/io/iohk/ethereum/SpecBase.scala
- src/test/scala/io/iohk/ethereum/WithActorSystemShutDown.scala
- src/test/scala/io/iohk/ethereum/consensus/ethash/EthashMinerSpec.scala
- src/test/scala/io/iohk/ethereum/consensus/ethash/MinerSpecSetup.scala
- src/test/scala/io/iohk/ethereum/consensus/ethash/MockedMinerSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JRCMatchers.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/QAServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/QaJRCSpec.scala
- mocked miner implementation
- QA service (mining blocks using mocked miner, listing pending txs)
> [ECTM-80] QA Service + mocked miner

- .gitignore
- build.sbt
- project/plugins.sbt
- project/repo.nix
- repo.nix
- src/main/scala/io/iohk/ethereum/db/dataSource/RocksDbDataSource.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
- src/main/scala/io/iohk/ethereum/utils/Ref.scala
- src/test/scala/io/iohk/ethereum/keystore/KeyStoreImplSpec.scala
This PR fixes issues found when trying to run Mantis on Windows, that is:
- generating proper `.bat` files
- fixing the way `SecureRandom` instance is obtained
- KeyStore tests which were too UNIX-oriented
- Update RocksDB to latest version, so Ethereum fork doesn't need to be used
All tests, `sbt dist` and syncing from both sbt and dist package should work
> Etcm 52 make sure mantis works on windows

- src/ets/scala/io/iohk/ethereum/ets/blockchain/BlockchainTestConfig.scala
- src/ets/scala/io/iohk/ethereum/ets/blockchain/ScenarioSetup.scala
- src/main/scala/io/iohk/ethereum/consensus/ConsensusBuilder.scala
- src/main/scala/io/iohk/ethereum/consensus/ConsensusConfig.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/EthashConsensus.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/blocks/EthashBlockGenerator.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/validators/MockedPowBlockHeaderValidator.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/validators/StdValidatorsExecutor.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/validators/ValidatorsExecutor.scala
- src/main/scala/io/iohk/ethereum/consensus/validators/std/StdValidators.scala
- src/test/scala/io/iohk/ethereum/Mocks.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/ScenarioSetup.scala
- src/test/scala/io/iohk/ethereum/consensus/BlockGeneratorSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
A couple of mocked miner fixes:
- Adds the mocked miner as one of the allowed protocols
- Adds mocked pow validations so that imported blocks created by mock miner doesn't fail
Setup:
- mantis.consensus.protocol = mocked
- mantis.consensus.mining-enabled = true
- mantis.blockchains.network = "private"
- mantis.sync.do-fast-sync = false
And use the mocked miner QA endpoint to generate blocks
> [FIX] Add mocked miner validations

- build.sbt
After finally being able to build mantis locally with nix I could verify whether that renaming is still necessary. It seems that changes from #671 fixed the issue so project can be renamed back to `mantis`
> [Chore] Rename sbt project name back to mantis

- src/main/scala/io/iohk/ethereum/db/storage/AppStateStorage.scala
- src/test/scala/io/iohk/ethereum/db/storage/AppStateStorageSpec.scala
Added possibility to save the latest checkpoint number in AppStateStorage
- added test suite for AppStateStorage
> [etcm-74] Latest Checkpoint Block Number in AppStateStorage

- .gitignore
- insomnia_workspace.json
- src/main/scala/io/iohk/ethereum/jsonrpc/DebugJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/EthJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/QAJsonMethodsImplicits.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
According to Ethereum RPC Spec, Mantis lacks `eth_chainId` method, which makes it much harder to issue transactions from Luna.
PS. This PR got so big due to auto-formatting. Changes crucial for this task are really minimal (test for eth service, test for rpc controller, insomnia entry, controller entry, json codec, eth service method).
1. All tests should pass
2. `eth_chainId` in Insomnia should return configured value in hex format according to spec (https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/etclabscore/ethereum-json-rpc-specification/master/openrpc.json&uiSchema%5BappBar%5D%5Bui:input%5D=false)
> [ETCM-110] Add eth_chainId RPC method

- src/main/resources/application.conf
- src/main/resources/logback.xml
- src/main/scala/io/iohk/ethereum/faucet/FaucetApi.scala
- src/universal/conf/faucet.conf
- src/universal/conf/logging.conf
Add missing logging configuration to the faucet. 
Fix faucet dir path
> [ETCM-125] Fix faucet logging issue

- src/main/resources/application.conf
- src/main/resources/chains/etc-chain.conf
- src/main/resources/chains/testnet-internal-chain.conf
- src/main/scala/io/iohk/ethereum/consensus/ConsensusConfig.scala
- src/main/scala/io/iohk/ethereum/crypto/ECDSASignature.scala
- src/main/scala/io/iohk/ethereum/db/storage/BlockBodiesStorage.scala
- src/main/scala/io/iohk/ethereum/db/storage/BlockHeadersStorage.scala
- src/main/scala/io/iohk/ethereum/domain/BlockBody.scala
- src/main/scala/io/iohk/ethereum/domain/BlockHeader.scala
- src/main/scala/io/iohk/ethereum/domain/Checkpoint.scala
- src/main/scala/io/iohk/ethereum/rlp/RLPImplicits.scala
- src/main/scala/io/iohk/ethereum/utils/BlockchainConfig.scala
- src/main/scala/io/iohk/ethereum/utils/ByteStringUtils.scala
- src/main/scala/io/iohk/ethereum/utils/ConfigUtils.scala
- src/test/scala/io/iohk/ethereum/ObjectGenerators.scala
- src/universal/conf/consensus.conf
Ported checkpoint domain and configuration
- checkpoint class
- configuration fields for checkpointing
- update block header RLP decoder / encoder according to https://input-output.atlassian.net/wiki/spaces/EMU/pages/1681686614/Checkpointing#RLP-encoding-(affects-network-messages-with-headers) 
- sync with mainnet with a fresh database
> [ETCM-70-71] Checkpointing domain + Checkpointing configuration

- .buildkite/pipeline.nix
- .buildkite/shell.nix
- repo.nix
- shell.nix
- Adds a step to the Buildkite CI to check that the Nix expressions of the project are up-to-date. If they are not, it provides a patch as an artifact that the user can download and apply with `patch -p1 < nix-expr.patch`. This was done to make it easier for non-Nix users to update the dependencies of the project.
> Ensure Nix expressions are up to date in CI

- insomnia_workspace.json
- src/main/scala/io/iohk/ethereum/healthcheck/Healthcheck.scala
- src/main/scala/io/iohk/ethereum/healthcheck/HealthcheckResponse.scala
- src/main/scala/io/iohk/ethereum/healthcheck/HealthcheckResult.scala
- src/main/scala/io/iohk/ethereum/healthcheck/HealthcheckStatus.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerMetrics.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcHealthChecker.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcHealthcheck.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/NodeJsonRpcHealthChecker.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/server/http/BasicJsonRpcHttpServer.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpServer.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpsServer.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpServerSpec.scala
This healthcheck functionality needs to be back ported from the other project, given is needed for testnet cluster purposes.
Manually run the node and use:
```
curl --request GET \
--url http://127.0.0.1:8546/healthcheck \
--header 'cache-control: no-cache'
```
Expected response
```
{
"checks": [
{
"description": "listening",
"status": "OK"
},
{
"description": "peerCount",
"status": "OK"
},
{
"description": "earliestBlock",
"status": "OK"
},
{
"description": "latestBlock",
"status": "OK"
},
{
"description": "pendingBlock",
"status": "OK"
}
]
}
```
> [ETCM-48] Add json rpc http healthcheck

- src/main/scala/io/iohk/ethereum/blockchain/sync/PeersClient.scala
- src/main/scala/io/iohk/ethereum/network/EtcPeerManagerActor.scala
- src/main/scala/io/iohk/ethereum/network/PeerManagerActor.scala
- src/main/scala/io/iohk/ethereum/network/p2p/messages/CommonMessages.scala
More in detail logging of all the handshaked peers a node is connected to
> [Chore] Detailed logging of the handshaked peers

- src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcher.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherState.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockImporter.scala
- src/main/scala/io/iohk/ethereum/domain/BlockHeader.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherStateSpec.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/regular/RegularSyncSpec.scala
Fixes branch resolution when triggered at the beginning of the chain, that caused sync to end in irreparable case
Given 2 nodes
1. If both have chains of the same weight but forked (top block with number X), when node 1 requests the last blocks from node 2 it won't import any
This step results in node 1 logging: `Imported no blocks`
2. Node 2 extends it chain with several mined blocks
3. Node 1 asks for blocks starting from block X+1, but as node 2 forked they won't be concatenable
This step results in node 1 logging: 
Unknown branch, going back to block nr -2 in order to resolve branches
Invalidate blocks from -2
4. Next request from node 1 will be from an earlier block than X, ideally before the fork, node 1 currently gets stuck here with logging:
Strict Pick blocks from -2 to 10
Lowest …
> [ETCM-186] Fix strict pick with too few blocks

- src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockImporter.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/EthashBlockCreator.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
- src/main/scala/io/iohk/ethereum/ommers/OmmersPool.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
- src/test/scala/io/iohk/ethereum/ommers/OmmersPoolSpec.scala
Fix ommers calculation at pool level and remove addition of mined blocks that are not imported.
As a future improvement it would be nice to make the Ommers pool a more "independent" component that handle the removal  of ommers by its own.
- Query by parentBlockHash instead of blockNumber
Unit tests should passed + we monitoring this at testnet level.
> [ETCM-177] Fix Ommers pool

- nix/default.nix
- nix/pkgs/mantis/default.nix
- nix/sources.json
`mkSrc` is a Nix function that's supposed to do the Right Thing with the source so that its hash ends up matching Hydra.
I've factored it out to a separate git repo so that I don't have to keep copy/pasting it between projects.
> [ETCM-108] Factor out mkSrc

- src/it/scala/io/iohk/ethereum/txExecTest/util/DumpChainApp.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
- src/main/scala/io/iohk/ethereum/db/storage/StateStorage.scala
- src/main/scala/io/iohk/ethereum/domain/Block.scala
- src/main/scala/io/iohk/ethereum/domain/Blockchain.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/TestService.scala
- src/main/scala/io/iohk/ethereum/ledger/BlockImport.scala
- src/test/scala/io/iohk/ethereum/db/storage/StateStorageSpec.scala
- src/test/scala/io/iohk/ethereum/domain/BlockchainSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
added saving last checkpoint number during block save and rollback
- saving last checkpoint number to the memory and persisting it with best block number after cache persist during block save
- persisting last checkpoint number and best block number immediately during block remove
unit tests
> [ETCM-75] Support for checkpoint blocks in Blockchain

- build.sbt
- insomnia_workspace.json
- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/blockchain/sync/regular/RegularSync.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/CheckpointingJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/CheckpointingService.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
- src/test/resources/application.conf
- src/test/scala/io/iohk/ethereum/jsonrpc/CheckpointingJRCSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/CheckpointingServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/QaJRCSpec.scala
- src/universal/conf/testmode.conf
Ported Checkpointing JRC
- new checkpointing RPC API
- new endpoint - checkpointing_getLatestBlock
- new endpoint checkpointing_pushCheckpoint
use insomnia endpoints
> [ETCM-78 added checkpointing JRC

- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerEthSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerEthTransactionSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerFixture.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerPersonalSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/TestSetup.scala
JsonRpcControllerSpec file contained around 2000 lines of code. This is hard to maintain. Context for this PR: https://github.com/input-output-hk/mantis/pull/726#discussion_r503406911
Split it into tests related to:
- `JsonRpcControllerPersonalSpec` personal_XYZ
- `JsonRpcControllerEthTransactionSpec` related to eth transaction requests
- `JsonRpcControllerEthSpec` other eth requests
- `JsonRpcControllerSpec` other requests
Before split there were utility function extracted that simplify creating requests and creating JsonRpcService: `newJsonRpcController`, `newJsonRpcRequest` in https://github.com/input-output-hk/mantis/pull/734/commits/53283b73265c070be4b22062a3bbad7fab577a04
> [ETCM-126] split JsonRpcControllerSpec

- build.sbt
`-Xfatal-warnings` with `-Yno-unused-import` is pretty annoying. This PR fixes that
Disable fatal warnings when `mantisDev` system property or `MANTIS_DEV` env variable is set to `true`
Enabled parallel test execution for unit tests
> [Chore] Add dev mode to build definition

- src/main/scala/io/iohk/ethereum/domain/Blockchain.scala
- src/main/scala/io/iohk/ethereum/ledger/BlockPreparator.scala
- src/main/scala/io/iohk/ethereum/ledger/StxLedger.scala
- src/main/scala/io/iohk/ethereum/vm/BlockchainConfigForEvm.scala
- src/main/scala/io/iohk/ethereum/vm/EvmConfig.scala
- src/test/scala/io/iohk/ethereum/consensus/BlockGeneratorSpec.scala
Fix block generation.
BlockPreparator didn't work correctly in case of an empty account (with value == 0). The change was introduced in EIP-161
> [ECTM-212] Fix block preparation (taking into account EIP-161)

- src/main/scala/io/iohk/ethereum/blockchain/sync/PivotBlockSelector.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/PivotBlockSelectorSpec.scala
Fixes a bug in pivot block selector
> [FIX Fix bug in pivot block selector

- insomnia_workspace.json
- src/ets/scala/io/iohk/ethereum/ets/blockchain/ScenarioSetup.scala
- src/main/scala/io/iohk/ethereum/consensus/ConsensusConfig.scala
- src/main/scala/io/iohk/ethereum/consensus/ConsensusConfigBuilder.scala
- src/main/scala/io/iohk/ethereum/crypto/ECDSASignature.scala
- src/main/scala/io/iohk/ethereum/crypto/package.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/QAJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/QAService.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/QAServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/QaJRCSpec.scala
Checkpointing helpers for QA
Add to new JRC methods:
- `qa_getFederationMembersInfo
- `qa_generateCheckpoint`
Unit tests + manual testing with Insomnia performed
> [ETCM-79] checkpointing QA JRC

- src/main/scala/io/iohk/ethereum/cli/CliCommands.scala
- src/test/scala/io/iohk/ethereum/cli/CliCommandsSpec.scala
Fix address derivation (address length)
> [ETCM-202] Fix address derivation command

- src/main/scala/io/iohk/ethereum/consensus/blocks/CheckpointBlockGenerator.scala
- src/main/scala/io/iohk/ethereum/consensus/validators/BlockHeaderValidator.scala
- src/main/scala/io/iohk/ethereum/consensus/validators/BlockWithCheckpointHeaderValidator.scala
- src/main/scala/io/iohk/ethereum/crypto/ECDSASignature.scala
- src/test/scala/io/iohk/ethereum/checkpointing/CheckpointingTestHelpers.scala
- src/test/scala/io/iohk/ethereum/consensus/validators/BlockWithCheckpointHeaderValidatorSpec.scala
Sort checkpoint signatures lexicographically to prevent having the same checkpoint block with a different hash (different order of signatures).
**Remember about changes on OBFT node side.**
- added validator of lexicographical order of checkpoint signatures
> [ETCM-174] Sorting of checkpoint signatures

- build.sbt
- src/main/scala/io/iohk/ethereum/jsonrpc/CheckpointingJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/DebugJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/EthJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/IeleJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcError.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/PersonalService.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/QAJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/QAService.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/TestJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/serialization/JsonEncoder.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/serialization/JsonMethodCodec.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/serialization/JsonMethodDecoder.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/serialization/JsonSerializers.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpServer.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/server/ipc/JsonRpcIpcServer.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/CheckpointingJRCSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerEthSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerEthTransactionSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerPersonalSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/PersonalServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/QAServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/QaJRCSpec.scala
Report custom eth error "100 missing data" when getting data from account
implementation of https://eth.wiki/json-rpc/json-rpc-error-codes-improvement-proposal (at least in account-touching methods)
Reorganized a bit json serialization. Due to nasty error I run into at some point (json4s and its formats <3) I wanted to plug Encoder-based serialization into rpc servers, due to multiple issues I stopped that and got into working state
Call methods like `eth_getBalance` during fast-sync - it should return error with additional information that state node is missing
> Etcm 139 incomplete data errors during fast sync

- src/main/scala/io/iohk/ethereum/utils/Config.scala
Async config was built improperly causing to node to fail
Run the node - it should not break now.
> [FIX] Fix the way AsyncConfig is built

- src/main/resources/chains/etc-chain.conf
- src/main/resources/chains/eth-chain.conf
- src/main/resources/chains/mordor-chain.conf
- src/main/resources/chains/ropsten-chain.conf
- src/main/resources/chains/test-chain.conf
- src/main/resources/chains/testnet-internal-chain.conf
- src/main/scala/io/iohk/ethereum/consensus/blocks/BlockGeneratorSkeleton.scala
- src/test/scala/io/iohk/ethereum/consensus/BlockGeneratorSpec.scala
Fixes how extra fields from blocks are generated after ECIP1097 activation.
We were currently not considering ECIP1097 (checkpoiting) when generating blocks, so they were still generated with HefECIP1098 (treasury), and no checkpoint field then. This made all post ECIP1097 blocks generated to marked as invalid.
Configure Mantis with:
- Mocked mining on
- ECIP1098 block number: 5
- ECIP1097 block number: 10
Start and mine more than 10 blocks, on develop, the block 10 generated would fail
- Unit tests added to block generator
- Follow the scenario described above, it should no longer fail
> [Fix] Non checkpoint blocks after ECIP1097 should have HefPostEcip1097 extra fields

- src/ets/scala/io/iohk/ethereum/ets/blockchain/BlockchainTestConfig.scala
- src/it/scala/io/iohk/ethereum/txExecTest/ECIP1017Test.scala
- src/it/scala/io/iohk/ethereum/txExecTest/ForksTest.scala
- src/main/resources/chains/etc-chain.conf
- src/main/resources/chains/eth-chain.conf
- src/main/resources/chains/mordor-chain.conf
- src/main/resources/chains/ropsten-chain.conf
- src/main/resources/chains/test-chain.conf
- src/main/resources/chains/testnet-internal-chain.conf
- src/main/scala/io/iohk/ethereum/consensus/ethash/EthashBlockCreator.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/EthashConsensus.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/EthashMiner.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/EthashUtils.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/validators/EthashBlockHeaderValidator.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
- src/main/scala/io/iohk/ethereum/utils/BlockchainConfig.scala
- src/test/resources/application.conf
- src/test/scala/io/iohk/ethereum/consensus/BlockGeneratorSpec.scala
- src/test/scala/io/iohk/ethereum/consensus/ethash/EthashUtilsSpec.scala
- src/test/scala/io/iohk/ethereum/consensus/validators/BlockHeaderValidatorSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/PersonalServiceSpec.scala
- src/test/scala/io/iohk/ethereum/ledger/StxLedgerSpec.scala
https://ecips.ethereumclassic.org/ECIPs/ecip-1099
> [ETCM-109] ECIP-1099 implementation

- src/it/scala/io/iohk/ethereum/txExecTest/ContractTest.scala
- src/it/scala/io/iohk/ethereum/txExecTest/ECIP1017Test.scala
- src/it/scala/io/iohk/ethereum/txExecTest/ForksTest.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/BlockResponse.scala
- src/main/scala/io/iohk/ethereum/ledger/BlockExecution.scala
- src/main/scala/io/iohk/ethereum/ledger/BlockImport.scala
- src/snappy/scala/io/iohk/ethereum/snappy/SnappyTest.scala
- src/test/scala/io/iohk/ethereum/checkpointing/CheckpointingTestHelpers.scala
- src/test/scala/io/iohk/ethereum/consensus/BlockGeneratorSpec.scala
- src/test/scala/io/iohk/ethereum/domain/BlockchainSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerEthSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerFixture.scala
- src/test/scala/io/iohk/ethereum/ledger/BlockExecutionSpec.scala
- src/test/scala/io/iohk/ethereum/ledger/BlockImportSpec.scala
- src/test/scala/io/iohk/ethereum/ledger/LedgerSpec.scala
All checkpoint blocks will currently be marked as invalid, as:
the block state root is set as the same as the parent
the resulting state root includes money provided to the coinbase address
The solution is a small optimization - block with checkpoint is skipping execution of transactions and paying the reward
- block with checkpoint is not executing transactions, rewards and after execution validation
- [bonus] added information about treasury and checkpoint to the json BlockResponse (I found it useful for testing)
unit tests + local tests with mocked miner and QA endpoints
> [ETCM-284] Pay no money to coinbase address when processing checkpoint blocks

- src/main/scala/io/iohk/ethereum/ledger/BlockExecution.scala
- src/test/scala/io/iohk/ethereum/BlockHelpers.scala
- src/test/scala/io/iohk/ethereum/ledger/BlockExecutionSpec.scala
- src/test/scala/io/iohk/ethereum/ledger/LedgerTestSetup.scala
Fixes missing blocks on testnet, caused by:
1. An invalid block (1505: 0b) was generated by the miner of the node (due to https://jira.iohk.io/browse/ETCM-301), probably caused by an expected race condition between the miner and the importing process
2. The above block import required a reorg of more than one block. From [1502: 8c, 1503: 87, 1504: 6c] to [1502: 8a, 1503: 5a, 1504: 0b, 1505: 0b] (the list are: [block number: first two bytes of the hash])
3. Failure in executing it caused the reorg to be reverted and `BlockImport.revertChainReorganisation` to be called with the `executedBlocks=[1505: 0b, 1504: 0b, 1503: 5a, 1502: 8a]`
4. This caused the call: `removeBlocksUntil(0b, 1502)`, meaning that all blocks from the db were deleted
5. Eventually block 1506 had an ommer whose parent …
> [FIX] Return executed blocks sorted on execution error

- src/main/resources/application.conf
- src/main/resources/chains/testnet-internal-genesis.json
- src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcher.scala
- src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherState.scala
Propagation improvements required for the testnet
- Changed max-xxx-peers configurations to match the other project. Note that the effect of them might be a bit unreliable due to our bad usage of them, this will be improved a bit with #763 
- Increased branch-resolution-request-size to 30 to be more resilient to reorgs
- Increased timestamp of the genesis block and it's difficulty, for the testnet to be closer to the 15 second target time per blocks. Without this, the difficult moved toward that direction, but it would take quite a while to reach there.
- Removed validation of NewBlockHashes message so that know top is always updated when one is received, as is the case with NewBlock messages
> [Fix] Propagation improvements

- src/ets/scala/io/iohk/ethereum/ets/blockchain/EthashTestBlockHeaderValidator.scala
- src/main/resources/chains/etc-chain.conf
- src/main/resources/chains/eth-chain.conf
- src/main/resources/chains/mordor-chain.conf
- src/main/resources/chains/ropsten-chain.conf
- src/main/resources/chains/test-chain.conf
- src/main/resources/chains/testnet-internal-chain.conf
- src/main/scala/io/iohk/ethereum/consensus/difficulty/ConstantDifficulty.scala
- src/main/scala/io/iohk/ethereum/consensus/difficulty/DifficultyCalculator.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/EthashConsensus.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/difficulty/EthashDifficultyCalculator.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/difficulty/TargetTimeDifficultyCalculator.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/validators/EthashBlockHeaderValidator.scala
- src/main/scala/io/iohk/ethereum/consensus/ethash/validators/MockedPowBlockHeaderValidator.scala
- src/main/scala/io/iohk/ethereum/testmode/TestmodeConsensus.scala
- src/main/scala/io/iohk/ethereum/utils/BlockchainConfig.scala
- src/test/resources/application.conf
Due to OBFT constraints, our internal testnet will have a higher target time between blocks than ETC, so we should make the block rate configurable for changing it on the different environments.
Introduced new Difficulty calculator which will try to compute difficulty to target configured PoW time
- new blockchain configuration key - `pow-target-time` (default is null which means that normal ethash calculator will be used)
> [ETCM-193] Make target time between blocks configurable

- src/main/scala/io/iohk/ethereum/ledger/BlockValidation.scala
Addresses issue on testnet
- Importing a chain of 12 blocks (1858 - 1870)
- Block 1870 had an ommer of number 1865 (it's chain ancestor is then block 1864)
When importing block 1970:
1. Blocks 1858-1869 were returned from the BlockQueue when fetching the branch from it
2. Taking 6 blocks from it resulted in blocks: 1858-1863
The above chain didn't have the ommer ancestor, so the validation of them failed with `OmmersAncestorsError`. As the above mentioned chain was followed by 3/5 miners they forked irrecoverably.
Changing `Taking 6 blocks from it resulted in blocks: 1858-1863` to `Taking the last 6 blocks from it resulted in blocks: 1864-1869`
Due to the complexity of testing this scenario and the time requirements for the having the internal testnet running no test was added.
> [FIX] Return the last blocks when fetching the ommers ancestors from memory

- insomnia_workspace.json
- src/universal/conf/faucet.conf
- Revert Faucet's port from 8547 to default 8099. 
- Remove legacy cors, used in the httpserver removed. Today the current cors used is “mantis.network.http.cors-allowed-origins” into the faucet config
> [ETCM-341] faucet - revert configs

- src/main/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcher.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/regular/BlockFetcherSpec.scala
Address forking issue on the testnet
During the startup of the nomad cluster there were some connectivity problems and some connections got closed resulting in timeouts on the requests. However for mantis-5
1. He sent a request for a block header to a peer whose connection was closing (or soon to be closed)
2. The request eventually died due to a timeout (or at least that's my theory), we can see that it died as the requesters logging of PeersClient reached 0 at some moment.
3. But the BlockFetcher never received that timeout, so it was permanently stuck on `fetching headers == true`
Recover from ask pattern timeout on the BlockFetcher by using the error fallback, which results in the request being cancelled and a new one triggered
Added unit test
> [FIX] Handle timeouts on BlockFetcher

- insomnia_workspace.json
- src/it/scala/io/iohk/ethereum/sync/util/CommonFakePeer.scala
- src/main/resources/application.conf
- src/main/scala/io/iohk/ethereum/jsonrpc/EthJsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonMethodsImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/MantisJsonMethodImplicits.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/MantisService.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/TransactionResponse.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/serialization/JsonEncoder.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
- src/main/scala/io/iohk/ethereum/transactions/TransactionHistoryService.scala
- src/test/resources/application.conf
- src/test/scala/io/iohk/ethereum/blockchain/sync/EphemBlockchainTestSetup.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/StateSyncSpec.scala
- src/test/scala/io/iohk/ethereum/domain/BlockchainSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/CheckpointingJRCSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerEthSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerEthTransactionSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerFixture.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/MantisJRCSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/MantisServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/QaJRCSpec.scala
- src/test/scala/io/iohk/ethereum/transactions/TransactionHistoryServiceSpec.scala
- src/test/scala/io/iohk/ethereum/transactions/testing/PendingTransactionsManagerAutoPilot.scala
- src/test/scala/io/iohk/ethereum/utils/VersionInfoSpec.scala
- src/universal/conf/testmode.conf
Move transaction history method to `mantis_` namespace, and add couple of additional informations a requested by Mantis Wallet devs.
It's a high priority because it's quite important from wallet perspective.
1. all unit tests should pass
2. check if method complains about too large number of blocks within range
3. check whether method finds transactions sent or received by given address (only direct sender or direct receiver is supported so far), example tx on mordor: https://blockscout.com/etc/mordor/tx/0x6249ce7bae7e6c57b08f4a9333bd335a9c001b648e2b62b30c4cea8e80fa9842/internal-transactions, it's a tx from faucet to my testing address
> [ETCM-135] Tx history improvements for wallet

- src/main/scala/io/iohk/ethereum/consensus/ConsensusBuilder.scala
- src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/MantisServiceSpec.scala
Previous PR caused NPE to be thrown during building whole cake of `Node`
> [FIX] Fix NPE thrown during cake building

- README.md
- src/main/scala/io/iohk/ethereum/cli/CliCommands.scala
- src/main/scala/io/iohk/ethereum/crypto/EcKeyGen.scala
- src/test/scala/io/iohk/ethereum/cli/CliCommandsSpec.scala
Add possibility to generate n keys (ported from other project)
> [ETCM-411] Add optional param to generate more keys at once

- src/main/scala/io/iohk/ethereum/crypto/ECDSASignature.scala
- src/test/scala/io/iohk/ethereum/crypto/ECDSASignatureSpec.scala
`ECDSASignature.recoverPubBytes` is using an external library code which is throwing exceptions.
Use `Try` in `ECDSASignature.recoverPubBytes` method.
> [Fix] - Made public key from signature recover method safer

- src/main/resources/chains/testnet-internal-nomad-chain.conf
Prepare our nomad testnet for deploying the treasury contract
Due to our check of account existance on the block execution, the treasury contract can be deployed on an testnet with ECIP 1098 already enabled by:
1. @KonradStaniec created the contract deploying account (`0xfca4134ea4203dbfeffbe55f8568ac2ff41f5f7f`) and derivated the expected treasury address (`0x0358e65dfe67b350eb827ffa17a82e7bb5f4c0c6`)
2. This PR, add it to our configurations (it's a requirement that the treasury address before it to never be used)
3. Deploy the treasury contract
Connect to the nomad testnet and execute blocks without any issues
> [Chore] Configure the future address of the treasury contract (nomad testnet)

- src/main/scala/io/iohk/ethereum/App.scala
- src/main/scala/io/iohk/ethereum/crypto/ECDSASignature.scala
- src/main/scala/io/iohk/ethereum/crypto/SignatureValidator.scala
- src/universal/bin/signatureValidator
We add a signature validation tool allowing the OBFT team to create a automated integration test checking the signatures issued by Morpho.
We also pad the ECDSA Signature `bigInt2Bytes` output.
Note: this has been tested using the Morpho integration test suite:
https://hydra.project42.iohkdev.io/log/lak4pp2cy1ych2kzzm5d7lr4dx7jnmv4-checkpointing-node-mantis-integration-tests.drv
```
unpacking sources
unpacking source archive /nix/store/0zyf6r2rlypf8la9prn6ks1105cz9hww-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
Mantis Integration Tests
mantis-integration
Test the keygen against the actual Mantis parser: OK (136.19s)
+++ OK, passed 100 tests.
All 1 tests passed (136.19s)
@nix { "action": …
```
> Add signature validation tool + fix checkpointing padding.

- src/main/scala/io/iohk/ethereum/ledger/BlockImport.scala
- src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
We were measuring block metrics after the block execution but before validation, which mean that we were measuring blocks which could be removed later.
Moved measuring block metrics to the place after the block execution and validation.
> [FIX] Moved block metrics to the place after validation and execution of the block

- src/main/resources/application.conf
Our `PeerActor` uses this option to retry outgoing connection when initial try fails. Setting it to `1 minute` means that this actor sits and do nothing for 1 minute, while taking `PeerManagerActor` outgoing connection slot. It can slow down acquiring new connections. In our other project we also tweaked that option. 
In longer perspective we should probably delete this mechanism, and make `PeerManagerActor` one thing responsible for initiating connections and re-connection.
> [FIX] Fix retry config option

- project/Dependencies.scala
- project/repo.nix
- repo.nix
- src/main/scala/io/iohk/ethereum/domain/Address.scala
- src/main/scala/io/iohk/ethereum/domain/SignedTransaction.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/MantisJsonMethodImplicits.scala
- src/main/scala/io/iohk/ethereum/transactions/TransactionHistoryService.scala
- src/test/scala/io/iohk/ethereum/BlockHelpers.scala
- src/test/scala/io/iohk/ethereum/Mocks.scala
- src/test/scala/io/iohk/ethereum/ObjectGenerators.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/BlockBroadcastSpec.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/PivotBlockSelectorSpec.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/SyncSchedulerSpec.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/TestSyncPeers.scala
- src/test/scala/io/iohk/ethereum/blockchain/sync/regular/RegularSyncFixtures.scala
- src/test/scala/io/iohk/ethereum/cli/CliCommandsSpec.scala
- src/test/scala/io/iohk/ethereum/consensus/BlockGeneratorSpec.scala
- src/test/scala/io/iohk/ethereum/crypto/ECDSASignatureSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/MantisJRCSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/MantisServiceSpec.scala
- src/test/scala/io/iohk/ethereum/jsonrpc/server/http/JsonRpcHttpServerSpec.scala
- src/test/scala/io/iohk/ethereum/network/EtcPeerManagerSpec.scala
- src/test/scala/io/iohk/ethereum/network/handshaker/EtcHandshakerSpec.scala
- src/test/scala/io/iohk/ethereum/network/p2p/MessageDecodersSpec.scala
- src/test/scala/io/iohk/ethereum/network/p2p/PeerActorSpec.scala
- src/test/scala/io/iohk/ethereum/network/p2p/messages/MessagesSerializationSpec.scala
- src/test/scala/io/iohk/ethereum/network/p2p/messages/ReceiptsSpec.scala
- src/test/scala/io/iohk/ethereum/transactions/TransactionHistoryServiceSpec.scala
This PR adds information about tx being in checkpointed block or not to `mantis_getAccountTransactions`.
Also, as it is very useful - in this PR I've added a dependency on diffx - library which highlights the differences in compared data.
All tests should pass. One can also try to use `qa_generateCheckpoint` for adding a checkpoint and checking if transactions from lower blocks are properly marked
> [ETCM-205] Add information about checkpoints in tx history

- src/main/scala/io/iohk/ethereum/ledger/BlockImport.scala
- src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
Measure block execution metrics on reorg as well.
The current measuring point is only part of the possible paths of blocks execution, meaning that some imported blocks are currently not measured
> [FIX] Trigger block execution metrics on reorg as well

- project/Dependencies.scala
- repo.nix
Includes 2 countermeasures against eclipse attacks and a bugfix:
* https://github.com/input-output-hk/scalanet/pull/108
* https://github.com/input-output-hk/scalanet/pull/109
* https://github.com/input-output-hk/scalanet/pull/110
> ETCM-[414,416,443]: Update to Scalanet 0.4.4

- src/main/resources/chains/testnet-internal-nomad-chain.conf
_Fix to add Checkpointing Federation keys under the Nomad's testnet configuration_
> [HotFix] To add Checkpointing Federation keys under the Nomad's testnet configuration

- src/main/scala/io/iohk/ethereum/domain/Address.scala
- src/main/scala/io/iohk/ethereum/jsonrpc/JsonMethodsImplicits.scala
Empty string should not be validated as the correct address
> [FIX] Empty address handling
