input-output-hk/mantis

build.sbt
src/it/scala/io/iohk/ethereum/mpt/MerklePatriciaTreeIntegrationSuite.scala
src/main/resources/application.conf
src/main/resources/logback.xml
src/main/scala/io/iohk/ethereum/network/TestSocketHandshaker.scala
src/main/scala/io/iohk/ethereum/utils/Logger.scala
src/test/resources/logback-test.xml
src/test/scala/io/iohk/ethereum/rlp/RLPSpeedSuite.scala
src/test/scala/io/iohk/ethereum/rlp/RLPSuite.scala

File + stdout in app, stdout only in tests

Add logback logging

---

.gitignore
scalastyle-config.xml
src/main/scala/io/iohk/ethereum/vm/DataWord.scala
src/test/scala/io/iohk/ethereum/vm/DataWordSpec.scala

Please read the documentation in code to see what a `DataWord` is. Ping me if anything is not clear enough.

Add an implementation and tests for a DataWord

---

src/main/resources/application.conf
src/main/scala/io/iohk/ethereum/network/PeerActor.scala
src/main/scala/io/iohk/ethereum/utils/Config.scala

Remaining parameters were moved to config file

[EC-53] Cleanup of constants

---

scalastyle-config.xml
src/main/scala/io/iohk/ethereum/vm/DataWord.scala
src/main/scala/io/iohk/ethereum/vm/OpCode.scala
src/test/scala/io/iohk/ethereum/vm/DataWordSpec.scala
src/test/scala/io/iohk/ethereum/vm/OpCodeFunSpec.scala
src/test/scala/io/iohk/ethereum/vm/OpCodeGasSpec.scala
src/test/scala/io/iohk/ethereum/vm/OpCodeTesting.scala

Introduces all missing `0`s and `10`s opcodes plus a few minor formatting changes.

[EC-76] EVM Stop, Arithmetic, Comparison and Bitwise opcodes

---

src/it/scala/io/iohk/ethereum/mpt/MerklePatriciaTreeIntegrationSuite.scala
src/main/scala/io/iohk/ethereum/blockchain/sync/FastSyncNodesRequestHandler.scala
src/main/scala/io/iohk/ethereum/crypto/package.scala
src/main/scala/io/iohk/ethereum/domain/BlockHeader.scala
src/main/scala/io/iohk/ethereum/domain/SignedTransaction.scala
src/main/scala/io/iohk/ethereum/network/p2p/messages/PV63.scala
src/main/scala/io/iohk/ethereum/network/p2p/validators/BlockHeaderValidator.scala
src/main/scala/io/iohk/ethereum/network/p2p/validators/BlockValidator.scala
src/main/scala/io/iohk/ethereum/network/p2p/validators/MptListValidator.scala
src/main/scala/io/iohk/ethereum/network/rlpx/AuthHandshaker.scala
src/main/scala/io/iohk/ethereum/vm/OpCode.scala
src/test/scala/io/iohk/ethereum/mpt/MerklePatriciaTrieSuite.scala
src/test/scala/io/iohk/ethereum/network/p2p/messages/NodeDataSpec.scala
src/test/scala/io/iohk/ethereum/network/p2p/messages/ReceiptsSpec.scala
src/test/scala/io/iohk/ethereum/network/p2p/messages/TransactionSpec.scala
src/test/scala/io/iohk/ethereum/vm/OpCodeFunSpec.scala

changed name of sha3 to kec256 and sha512 to kec512

[EC-89] Accurately name sha3 functions in crypto

---

src/main/scala/io/iohk/ethereum/network/p2p/validators/BlockValidator.scala
src/universal/conf/application.conf

Moves configuration added to `resources/application.conf` to `universal/conf/application.conf` that caused the zipped project not to work. Also changed some comments to remove warnings when using `sbt dist`.

Added configuration to universal/conf/application.conf

---

src/main/resources/application.conf
src/main/scala/io/iohk/ethereum/App.scala
src/main/scala/io/iohk/ethereum/blockchain/sync/RegularSyncController.scala
src/main/scala/io/iohk/ethereum/blockchain/sync/SyncController.scala
src/main/scala/io/iohk/ethereum/db/storage/AppStateStorage.scala
src/main/scala/io/iohk/ethereum/utils/Config.scala
src/test/scala/io/iohk/ethereum/blockchain/sync/SyncControllerSpec.scala
src/test/scala/io/iohk/ethereum/rpc/BlockControllerSpec.scala

Add check to prevent fast sync to be executed more then once
This PR should be merged after https://github.com/input-output-hk/etc-client/pull/88 which is based on.

EC-130 Resume regular download if fast sync is done

---

src/evmTest/scala/io/iohk/ethereum/vm/MinimumViableTokenSpec.scala
src/main/scala/io/iohk/ethereum/vm/EvmConfig.scala

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2.mediawiki was misread. (21000 + 32000 = 53000)
Consult YP appendix G

fix G_txcreate fees

---

src/main/scala/io/iohk/ethereum/App.scala
src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
src/main/scala/io/iohk/ethereum/mpt/MerklePatriciaTrie.scala
src/main/scala/io/iohk/ethereum/vm/EvmConfig.scala
src/main/scala/io/iohk/ethereum/vm/ProgramContext.scala

Includes several fixes to issues detected while running different static analysis tools.
The main problems fixed were:
* Removed unused method parameters.
* Parantheless call to methods with effect and returning unit.

Static analysis tools fixes

---

src/evmTest/scala/io/iohk/ethereum/vm/PrecompiledContractsSpec.scala
src/main/scala/io/iohk/ethereum/crypto/package.scala
src/main/scala/io/iohk/ethereum/vm/PrecompiledContracts.scala
src/test/scala/io/iohk/ethereum/vm/CallOpcodesSpec.scala
src/test/scala/io/iohk/ethereum/vm/PrecompiledContractsSpec.scala

precompiled contract should use sha256, not kec256 (sha3)

---

src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
src/test/scala/io/iohk/ethereum/ledger/LedgerSpec.scala

The issue was that we did not create accounts for sender address when it does not exists which is an issue for transactions with gas price set to 0 which are valid transactions.

[EC-171] Error in block 3003036

---

src/main/resources/application.conf
src/main/scala/io/iohk/ethereum/jsonrpc/JsonMethodsImplicits.scala
src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
src/main/scala/io/iohk/ethereum/jsonrpc/NetService.scala
src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
src/main/scala/io/iohk/ethereum/utils/Config.scala
src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
src/test/scala/io/iohk/ethereum/jsonrpc/NetServiceSpec.scala

Add net_ rpc methods

---

src/main/scala/io/iohk/ethereum/jsonrpc/EthJsonMethodsImplicits.scala
src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala

This PR adds `eth_hashrate` and implements `eth_submitHashrate`
it depends on #193

[EC-183] Add hashrate reporting

---

src/main/scala/io/iohk/ethereum/blockchain/sync/SyncController.scala
src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
src/main/scala/io/iohk/ethereum/jsonrpc/PersonalService.scala
src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
src/test/scala/io/iohk/ethereum/blockchain/sync/SyncControllerSpec.scala
src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
src/test/scala/io/iohk/ethereum/jsonrpc/PersonalServiceSpec.scala

Includes several fixes to issues detected while running different static analysis tools.
The problems fixed were:
* Removed unused imports
* Removed unused `blockchainConfig` parameter and unused `DependencyActors` case class.

Linting tools fixes

---

src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala

Needed to connect geth console

Add rpc_modules api

---

src/main/scala/io/iohk/ethereum/vm/OpCode.scala
src/test/scala/io/iohk/ethereum/vm/CreateOpcodeSpec.scala

Fixes 2 bugs:
- no step on error in CREATE
- creator's nonce not increased after creation failure

Fixed no step on error in CREATE

---

src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
src/main/scala/io/iohk/ethereum/validators/BlockValidator.scala
src/test/scala/io/iohk/ethereum/Mocks.scala
src/test/scala/io/iohk/ethereum/blockchain/sync/SyncControllerSpec.scala

this PR adds validation for block bodies in fast sync

[EC-249] Block bodies validation during FastSync

---

src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
src/main/scala/io/iohk/ethereum/blockchain/sync/FastSyncReceiptsRequestHandler.scala
src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
src/main/scala/io/iohk/ethereum/validators/BlockValidator.scala
src/test/scala/io/iohk/ethereum/Mocks.scala
src/test/scala/io/iohk/ethereum/blockchain/sync/FastSyncReceiptsRequestHandlerSpec.scala
src/test/scala/io/iohk/ethereum/ledger/LedgerSpec.scala

Add validating receipts received during FastSync, to detect whether we receive an invalid response (as happened in bootstrap db for block `1532165`).

[EC-287] Validate receipts received during FastSync

---

src/it/scala/io/iohk/ethereum/txExecTest/ContractTest.scala
src/it/scala/io/iohk/ethereum/txExecTest/ForksTest.scala
src/it/scala/io/iohk/ethereum/txExecTest/util/DumpChainApp.scala
src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
src/main/scala/io/iohk/ethereum/blockchain/sync/FastSyncNodesRequestHandler.scala
src/main/scala/io/iohk/ethereum/blockchain/sync/RegularSync.scala
src/main/scala/io/iohk/ethereum/blockchain/sync/SyncController.scala
src/main/scala/io/iohk/ethereum/domain/Blockchain.scala
src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
src/main/scala/io/iohk/ethereum/mining/BlockGenerator.scala
src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
src/main/scala/io/iohk/ethereum/transactions/PendingTransactionsManager.scala
src/test/scala/io/iohk/ethereum/Mocks.scala
src/test/scala/io/iohk/ethereum/blockchain/sync/SyncControllerSpec.scala
src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
src/test/scala/io/iohk/ethereum/ledger/BlockRewardSpec.scala
src/test/scala/io/iohk/ethereum/ledger/DeleteAccountsSpec.scala
src/test/scala/io/iohk/ethereum/ledger/LedgerSpec.scala
src/test/scala/io/iohk/ethereum/ledger/ValidationsAfterExecutionSpec.scala
src/test/scala/io/iohk/ethereum/mining/BlockGeneratorSpec.scala

Reduced the passing of `BlockchainStorages` as a parameter and the construction of `BlockchainImpl` through out the codebase, so as to work just with `Blockchain` whenever possible.

[EC-253] Removed use of BlockchainStorages outside Blockchain

---

src/it/scala/io/iohk/ethereum/mpt/MerklePatriciaTreeIntegrationSuite.scala
src/it/scala/io/iohk/ethereum/txExecTest/util/DumpChainActor.scala
src/it/scala/io/iohk/ethereum/txExecTest/util/DumpChainApp.scala
src/it/scala/io/iohk/ethereum/txExecTest/util/FixtureProvider.scala
src/main/scala/io/iohk/ethereum/blockchain/data/GenesisDataLoader.scala
src/main/scala/io/iohk/ethereum/blockchain/sync/BlockchainHostActor.scala
src/main/scala/io/iohk/ethereum/blockchain/sync/FastSyncNodesRequestHandler.scala
src/main/scala/io/iohk/ethereum/domain/Blockchain.scala
src/main/scala/io/iohk/ethereum/domain/package.scala
src/main/scala/io/iohk/ethereum/ledger/InMemoryWorldStateProxy.scala
src/main/scala/io/iohk/ethereum/mining/BlockGenerator.scala
src/main/scala/io/iohk/ethereum/mpt/MerklePatriciaTrie.scala
src/main/scala/io/iohk/ethereum/mpt/Node.scala
src/main/scala/io/iohk/ethereum/network/p2p/messages/PV63.scala
src/main/scala/io/iohk/ethereum/validators/MptListValidator.scala
src/test/scala/io/iohk/ethereum/ObjectGenerators.scala
src/test/scala/io/iohk/ethereum/blockchain/sync/BlockchainHostActorSpec.scala
src/test/scala/io/iohk/ethereum/db/storage/NodeStorageSuite.scala
src/test/scala/io/iohk/ethereum/domain/BlockchainSpec.scala
src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
src/test/scala/io/iohk/ethereum/ledger/InMemorySimpleMapProxySpec.scala
src/test/scala/io/iohk/ethereum/mpt/MerklePatriciaTrieSuite.scala
src/test/scala/io/iohk/ethereum/network/p2p/messages/NodeDataSpec.scala

this PR removes mpt nodes from PV63

[EC-147] Decide on what to do with MPTNodeStorage and NodeStorage

---

README.md

Quick update of the README to allow for sbt-verify install.

Update README to include sbt-verify install

---

src/main/resources/application.conf
src/main/scala/io/iohk/ethereum/jsonrpc/server/JsonRpcHttpServer.scala
src/main/scala/io/iohk/ethereum/jsonrpc/server/JsonRpcHttpsServer.scala
src/main/scala/io/iohk/ethereum/jsonrpc/server/JsonRpcServer.scala
src/main/scala/io/iohk/ethereum/utils/Config.scala
src/test/scala/io/iohk/ethereum/jsonrpc/server/JsonRpcServerSpec.scala
src/universal/conf/network.conf

In order to incrase HTTP Json RPC endpoint security, this PR allows to:
- disable CORS
- enable cors for a specific domains

[EC-335] CORS configuration

---

src/universal/conf/network.conf

Expose the discovery port in the conf file.

Expose network discovery port

---

src/main/scala/io/iohk/ethereum/ledger/Ledger.scala

Ommers validation fix

---

src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
src/test/scala/io/iohk/ethereum/blockchain/sync/SyncControllerSpec.scala

I've also added a test that fails without this fix

Fix block enqueue in fast sync

---

src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
src/test/scala/io/iohk/ethereum/ledger/BlockImportSpec.scala

[EC-354](https://iohk.myjetbrains.com/youtrack/issue/EC-354)
~This is not a critical bug, so we probably want to merge it only after the next release.~
Since we're already fixing this area, we may as well go with this fix

[EC-354] fix branch resolution at genesis block

---

src/test/scala/io/iohk/ethereum/ledger/BlockImportSpec.scala

[EC-364] Test case to test ommers validation

---

src/main/resources/application.conf
src/main/scala/io/iohk/ethereum/blockchain/sync/RegularSync.scala
src/main/scala/io/iohk/ethereum/blockchain/sync/SyncController.scala
src/main/scala/io/iohk/ethereum/mpt/MerklePatriciaTrie.scala
src/main/scala/io/iohk/ethereum/utils/Config.scala
src/test/scala/io/iohk/ethereum/blockchain/sync/RegularSyncSpec.scala
src/test/scala/io/iohk/ethereum/blockchain/sync/SyncControllerSpec.scala

~~Proof of concept - poor code quality~~
[EC-368](https://iohk.myjetbrains.com/youtrack/issue/EC-368)

[EC-368] redownload missing state nodes

---

README.md
build.sbt
circle.yml
src/universal/RELEASE
src/universal/conf/network.conf

Update doco for command line version.

Change name

---

circle.yml
src/ets/resources/logback-test.xml
test-ets.sh

It was due to memory problems.. more info in the comment in the script

[EC-394] ETS failing on CircleCI

---

src/main/scala/io/iohk/ethereum/validators/BlockHeaderValidator.scala
src/test/scala/io/iohk/ethereum/validators/BlockHeaderValidatorSpec.scala

Yellow paper also states that gasUsed shoud belongs to positive
integers set

[EC-418] Validation that gasUsed is positive number

---

src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
src/test/scala/io/iohk/ethereum/ledger/BlockImportSpec.scala

[EC-401] Handling import of genesis block

---

src/main/resources/application.conf
src/main/scala/io/iohk/ethereum/jsonrpc/PersonalService.scala
src/main/scala/io/iohk/ethereum/keystore/KeyStore.scala
src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
src/main/scala/io/iohk/ethereum/utils/Config.scala
src/test/resources/application.conf
src/test/scala/io/iohk/ethereum/jsonrpc/PersonalServiceSpec.scala
src/test/scala/io/iohk/ethereum/keystore/KeyStoreImplSpec.scala
src/universal/conf/storage.conf

It would need changes also on Daedalus side.

[EC-421] Minimal passphrase length enforcement

---

src/main/scala/io/iohk/ethereum/consensus/atomixraft/AtomixRaftForger.scala
src/main/scala/io/iohk/ethereum/consensus/blocks/BlockGenerator.scala
src/main/scala/io/iohk/ethereum/consensus/blocks/BlockGeneratorSkeleton.scala
src/main/scala/io/iohk/ethereum/consensus/blocks/NoOmmersBlockGenerator.scala
src/main/scala/io/iohk/ethereum/consensus/ethash/blocks/EthashBlockGenerator.scala
src/test/scala/io/iohk/ethereum/consensus/BlockGeneratorSpec.scala

[cgkiele-142] Rename `ommers`

---

.circleci/Dockerfile
.circleci/config.yml
build.sbt
project/plugins.sbt
src/main/scala/io/iohk/ethereum/consensus/ConsensusConfig.scala
src/main/scala/io/iohk/ethereum/consensus/atomixraft/AtomixRaftConsensus.scala
src/main/scala/io/iohk/ethereum/consensus/atomixraft/blocks/AtomixRaftBlockGenerator.scala
src/main/scala/io/iohk/ethereum/consensus/atomixraft/difficulty/AtomixRaftDifficulty.scala
src/main/scala/io/iohk/ethereum/consensus/atomixraft/validators/AtomixRaftBlockHeaderValidator.scala
src/main/scala/io/iohk/ethereum/consensus/atomixraft/validators/AtomixRaftValidators.scala
src/main/scala/io/iohk/ethereum/consensus/atomixraft/validators/package.scala
src/main/scala/io/iohk/ethereum/consensus/blocks/BlockGeneratorSkeleton.scala
src/main/scala/io/iohk/ethereum/consensus/difficulty/ConstantDifficulty.scala
src/main/scala/io/iohk/ethereum/consensus/difficulty/DifficultyCalculator.scala
src/main/scala/io/iohk/ethereum/consensus/ethash/EthashConsensus.scala
src/main/scala/io/iohk/ethereum/consensus/ethash/blocks/EthashBlockGenerator.scala
src/main/scala/io/iohk/ethereum/consensus/ethash/blocks/package.scala
src/main/scala/io/iohk/ethereum/consensus/ethash/difficulty/EthashDifficultyCalculator.scala
src/main/scala/io/iohk/ethereum/consensus/ethash/validators/EthashBlockHeaderValidator.scala
src/main/scala/io/iohk/ethereum/consensus/ethash/validators/EthashValidators.scala
src/main/scala/io/iohk/ethereum/consensus/ethash/validators/StdEthashValidators.scala
src/main/scala/io/iohk/ethereum/consensus/validators/BlockHeaderValidator.scala
src/main/scala/io/iohk/ethereum/consensus/validators/BlockHeaderValidatorSkeleton.scala
src/main/scala/io/iohk/ethereum/consensus/validators/SignedTransactionValidator.scala
src/main/scala/io/iohk/ethereum/consensus/validators/std/StdValidators.scala
src/test/scala/io/iohk/ethereum/blockchain/sync/ScenarioSetup.scala
src/test/scala/io/iohk/ethereum/consensus/atomixraft/difficulty/DifficultySpec.scala
src/test/scala/io/iohk/ethereum/consensus/ethash/EthashMinerSpec.scala
src/test/scala/io/iohk/ethereum/consensus/validators/BlockHeaderValidatorSpec.scala
src/test/scala/io/iohk/ethereum/consensus/validators/OmmersValidatorSpec.scala

Some extra features are also present:
* Bump Scala version to `2.12.5`.
* Bump `sbt-verify` version to `0.4.1`.
* Have `sbt-verify` issue warnings instead of errors. This is a temporary solution to some inconsistent behaviour we have observed, so that the developer experience is a bit better.

[cgkiele-138,139] Polymorphic difficulty calculation & validation

---

.circleci/config.yml

scheduled tests were failing because of this

Update docker image for scheduled ETS

---

src/universal/conf/private-testnet.conf

RPC config structure has changed in testmode PR. private-testnet.conf needs a fix

Fix testnet config

---

build.sbt
src/main/scala/io/iohk/ethereum/mallet/interpreter/AST.scala
src/main/scala/io/iohk/ethereum/mallet/interpreter/CmdParser.scala
src/main/scala/io/iohk/ethereum/mallet/interpreter/Commands.scala
src/main/scala/io/iohk/ethereum/mallet/interpreter/Interpreter.scala
src/main/scala/io/iohk/ethereum/mallet/interpreter/Parameter.scala
verify.sbt

depends on #436 
Additional requirements for this PR:

[CGKIELE-107] mallet - IELE transactions

---

src/ets/scala/io/iohk/ethereum/ets/blockchain/BlockchainTestConfig.scala
src/ets/scala/io/iohk/ethereum/ets/blockchain/ScenarioSetup.scala
src/it/scala/io/iohk/ethereum/SimulateTransactionTest/SimulateTransactionTest.scala
src/it/scala/io/iohk/ethereum/txExecTest/ECIP1017Test.scala
src/it/scala/io/iohk/ethereum/txExecTest/ForksTest.scala
src/main/resources/application.conf
src/main/scala/io/iohk/ethereum/blockchain/data/GenesisDataLoader.scala
src/main/scala/io/iohk/ethereum/consensus/blocks/BlockGeneratorSkeleton.scala
src/main/scala/io/iohk/ethereum/consensus/validators/BlockHeaderValidatorSkeleton.scala
src/main/scala/io/iohk/ethereum/extvm/ExtVMInterface.scala
src/main/scala/io/iohk/ethereum/jsonrpc/TestService.scala
src/main/scala/io/iohk/ethereum/utils/Config.scala
src/test/scala/io/iohk/ethereum/consensus/BlockGeneratorSpec.scala
src/test/scala/io/iohk/ethereum/consensus/validators/BlockHeaderValidatorSpec.scala
src/test/scala/io/iohk/ethereum/jsonrpc/EthServiceSpec.scala
src/test/scala/io/iohk/ethereum/jsonrpc/PersonalServiceSpec.scala
src/test/scala/io/iohk/ethereum/ledger/LedgerSpec.scala
src/test/scala/io/iohk/ethereum/network/handshaker/EtcHandshakerSpec.scala
src/universal/conf/private-genesis.json
src/universal/conf/private-testnet.conf

- entry point to extvm is `synchronized` - this fixes `eth_call`, `eth_estimateGas` and normal transactions while on `ethash`
- configurable constant block gas limit
- `BlockchainConfig` as case class

[CKGIELE-189] synchronise extvm / constant block gas limit

---

src/main/resources/application.conf
src/main/scala/io/iohk/ethereum/consensus/atomixraft/AtomixRaftConfig.scala
src/main/scala/io/iohk/ethereum/consensus/atomixraft/AtomixRaftConsensus.scala
src/main/scala/io/iohk/ethereum/consensus/atomixraft/AtomixRaftForger.scala
src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
src/main/scala/io/iohk/ethereum/metrics/Metrics.scala
src/main/scala/io/iohk/ethereum/metrics/MetricsConfig.scala
src/universal/conf/consensus.conf
src/universal/conf/metrics.conf
src/universal/conf/private-testnet.conf

Also:
- Fix a bug with null `environment` and `deployment`
- Require non-empty values for the above when `enabled = true`
- Improve documentation in configuration

CGKIELE-168: Add more metrics

---

src/main/scala/io/iohk/ethereum/network/PeerManagerActor.scala
src/test/resources/application.conf
src/test/scala/io/iohk/ethereum/network/PeerManagerSpec.scala

All explanation under ticket: https://iohk.myjetbrains.com/youtrack/issue/EC-533

[EC-533] Fix bug when disconnecting from incomig peer

---

src/main/resources/application.conf
src/main/scala/io/iohk/ethereum/jsonrpc/DebugJsonMethodsImplicits.scala
src/main/scala/io/iohk/ethereum/jsonrpc/DebugService.scala
src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
src/main/scala/io/iohk/ethereum/nodebuilder/NodeBuilder.scala
src/test/resources/application.conf
src/test/scala/io/iohk/ethereum/jsonrpc/DebugServiceSpec.scala
src/test/scala/io/iohk/ethereum/jsonrpc/JsonRpcControllerSpec.scala
src/universal/conf/testmode.conf

- enable debug api in JsonRPCController
- create debug service and decode/encode methods
- add debug_listPeersInfo method to JsonRpcRequest

Introduce endpoint for peer info

---

src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala
src/main/scala/io/iohk/ethereum/jsonrpc/TransactionReceiptResponse.scala

It needs to be 1 or 0 (as int, not boolean as before).

Fix receipt status field for web3

---

src/main/scala/io/iohk/ethereum/blockchain/data/GenesisDataLoader.scala
src/main/scala/io/iohk/ethereum/blockchain/sync/FastSync.scala
src/main/scala/io/iohk/ethereum/blockchain/sync/FastSyncStateStorageActor.scala
src/main/scala/io/iohk/ethereum/blockchain/sync/RegularSync.scala
src/main/scala/io/iohk/ethereum/consensus/atomixraft/AtomixRaftConsensus.scala
src/main/scala/io/iohk/ethereum/consensus/atomixraft/AtomixRaftForger.scala
src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcController.scala
src/main/scala/io/iohk/ethereum/ledger/Ledger.scala
src/main/scala/io/iohk/ethereum/network/KnownNodesManager.scala
src/main/scala/io/iohk/ethereum/network/PeerManagerActor.scala
src/main/scala/io/iohk/ethereum/network/ServerActor.scala
src/main/scala/io/iohk/ethereum/network/handshaker/EtcForkBlockExchangeState.scala
src/main/scala/io/iohk/ethereum/network/handshaker/EtcHelloExchangeState.scala
src/main/scala/io/iohk/ethereum/network/handshaker/EtcNodeStatusExchangeState.scala
src/main/scala/io/iohk/ethereum/nodebuilder/StdNode.scala
src/main/scala/io/iohk/ethereum/utils/Config.scala
src/main/scala/io/iohk/ethereum/utils/Riemann.scala
src/main/scala/io/iohk/ethereum/utils/Scheduler.scala
src/main/scala/io/iohk/ethereum/utils/events/EventSupport.scala
src/main/scala/io/iohk/ethereum/utils/events/package.scala

This is intended as a PR review for #554 :-D

Riemann: add some DSL convenience and re-shape a few things

---

src/main/scala/io/iohk/ethereum/App.scala
src/main/scala/io/iohk/ethereum/blockchain/visitor/BlockchainListener.scala
src/main/scala/io/iohk/ethereum/blockchain/visitor/BlockchainVisitor.scala
src/main/scala/io/iohk/ethereum/blockchain/visitor/FullBlockchainVisitor.scala
src/main/scala/io/iohk/ethereum/blockchain/visitor/app/FindEmptyAccounts.scala

Traverse the blockchain to discover creation of empty accounts

---

src/ets/scala/io/iohk/ethereum/ets/blockchain/BlockchainSuite.scala
src/main/scala/io/iohk/ethereum/vm/OpCode.scala
src/test/scala/io/iohk/ethereum/vm/OpCodeFunSpec.scala
src/test/scala/io/iohk/ethereum/vm/OpCodeGasSpec.scala

Spec: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1052.md

EIP-1052 EXTCODEHASH opcode

---

src/ets/scala/io/iohk/ethereum/ets/vm/testopcodes.scala
src/main/scala/io/iohk/ethereum/vm/OpCode.scala
src/main/scala/io/iohk/ethereum/vm/VM.scala
src/main/scala/io/iohk/ethereum/vm/WorldStateProxy.scala
src/test/scala/io/iohk/ethereum/vm/CreateOpcodeSpec.scala
src/test/scala/io/iohk/ethereum/vm/OpCodeFunSpec.scala
src/test/scala/io/iohk/ethereum/vm/OpCodeGasSpec.scala

Spec: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1014.md

EIP-1014 Skinny CREATE2

---

build.sbt
src/main/scala/io/iohk/ethereum/App.scala
src/main/scala/io/iohk/ethereum/metrics/Metrics.scala
src/main/scala/io/iohk/ethereum/metrics/RiemannRegistry.scala
src/main/scala/io/iohk/ethereum/metrics/RiemannRegistryConfig.scala
src/main/scala/io/iohk/ethereum/utils/Config.scala
src/main/scala/io/iohk/ethereum/utils/Riemann.scala
src/main/scala/io/iohk/ethereum/utils/events/EventsDSL.scala
src/main/scala/io/iohk/ethereum/utils/events/package.scala
verify.sbt

Ref CGKIELE-557, CGKIELE-683, CGKIELE-684

Send all metrics to Riemann

---

src/main/scala/io/iohk/ethereum/vm/OpCode.scala
src/main/scala/io/iohk/ethereum/vm/ProgramState.scala
src/main/scala/io/iohk/ethereum/vm/VM.scala
src/test/scala/io/iohk/ethereum/vm/CreateOpcodeSpec.scala
src/test/scala/io/iohk/ethereum/vm/Fixtures.scala
src/test/scala/io/iohk/ethereum/vm/Generators.scala
src/test/scala/io/iohk/ethereum/vm/OpCodeGasSpec.scala
src/test/scala/io/iohk/ethereum/vm/SSTOREOpCodeGasPostConstantinopleSpec.scala

Spec: https://eips.ethereum.org/EIPS/eip-1283

EIP 1283 - Net gas metering for SSTORE without dirty maps

---

src/main/scala/io/iohk/ethereum/vm/OpCode.scala
src/main/scala/io/iohk/ethereum/vm/WorldStateProxy.scala

Small implementation fix + new fixed formula

EIP 1014 - fix

---

src/ets/scala/io/iohk/ethereum/ets/vm/ScenarioBuilder.scala
src/main/scala/io/iohk/ethereum/extvm/VMServer.scala
src/main/scala/io/iohk/ethereum/vm/OpCode.scala
src/main/scala/io/iohk/ethereum/vm/ProgramContext.scala
src/main/scala/io/iohk/ethereum/vm/ProgramState.scala
src/main/scala/io/iohk/ethereum/vm/VM.scala
src/test/scala/io/iohk/ethereum/vm/CallOpFixture.scala
src/test/scala/io/iohk/ethereum/vm/CreateOpcodeSpec.scala
src/test/scala/io/iohk/ethereum/vm/Generators.scala
src/test/scala/io/iohk/ethereum/vm/PrecompiledContractsSpec.scala
src/test/scala/io/iohk/ethereum/vm/SSTOREOpCodeGasPostConstantinopleSpec.scala
src/test/scala/io/iohk/ethereum/vm/ShiftingOpCodeSpec.scala
src/test/scala/io/iohk/ethereum/vm/VMSpec.scala

Fixing most of failing constantinipole ets tests (most errors were related to new sstore gas calculation)
Only one failing test remain: 
GeneralStateTests/stShift/sar_2^256-1_0_d0g0v

fix ets tests

---

src/main/resources/chains/eth.conf
src/main/resources/chains/ropsten.conf

eth and ropsten don not have concept of eras, so 1st era should last as long as possible 50 000 000 block is around 21 years.

fix configs

---

License Notice

Hi Alan and Ger, here the additional file required, please accept the pull request, thanks!

Create License Notice

---

src/main/scala/io/iohk/ethereum/vm/BlockchainConfigForEvm.scala
src/main/scala/io/iohk/ethereum/vm/OpCode.scala
src/main/scala/io/iohk/ethereum/vm/PrecompiledContracts.scala

https://eips.ethereum.org/EIPS/eip-1108

[ETCM-18] EIP-1108: Reduce alt_bn128 precompile gas costs

---

src/ets/scala/io/iohk/ethereum/ets/blockchain/BlockchainSuite.scala
src/ets/scala/io/iohk/ethereum/ets/blockchain/BlockchainTestConfig.scala
src/ets/scala/io/iohk/ethereum/ets/blockchain/ScenarioSetup.scala
src/ets/scala/io/iohk/ethereum/ets/blockchain/scenario.scala
src/main/resources/application.conf
src/main/scala/io/iohk/ethereum/ledger/BlockExecution.scala
src/main/scala/io/iohk/ethereum/ledger/BlockImport.scala
src/test/scala/io/iohk/ethereum/ledger/BlockQueueSpec.scala

[WIP] There are still 2 failing tests:
- `TransitionTests/bcHomesteadToDao/DaoTransactions`
- `ValidBlocks/bcForkStressTest/ForkStressTest`

[ETCM-27] Update and check ETS tests

---

src/main/scala/io/iohk/ethereum/db/dataSource/RocksDbDataSource.scala
src/main/scala/io/iohk/ethereum/db/storage/KeyValueStorage.scala

[ETCM-50] Fix db closing

---

insomnia_workspace.json

Add initial insomnia workspace file, further examples should be added when required/used

[CHORE] Add insomnia workspace example

---

repo.nix

[Chore] Update repo.nix with all dependencies

---

src/main/resources/logback.xml

Include date into the logging timestamp - it will be useful in logs parsing and tracking.

[Chore] Include date into the logging timestamp

---

project/Dependencies.scala
repo.nix
src/test/scala/io/iohk/ethereum/SpecBase.scala

Update typelevel (and related) libs to their recent versions
All tests should pass

[Chore] Update typelevel dependencies

---

README.md

Add missing info about the generic launcher script

[CHORE] Update README - add info about generic launcher script

---

src/universal/bin/faucet-server

Fix override configuration properties via CLI args for faucet launcher

[ETCM-187] Fix faucet launcher

---

repo.nix

At some point we merge a PR with changes in the project dependencies (scalanet) without update nix packages.

[Chore] Fix nix dependencies

---

repo.nix
src/main/scala/io/iohk/ethereum/jsonrpc/EthService.scala

[FIX] Repo nix fix

---

src/main/scala/io/iohk/ethereum/ledger/BlockImport.scala
src/main/scala/io/iohk/ethereum/ledger/BlockMetrics.scala

New metric - block with checkpoint number

[ETCM-339] [Metrics] Add metrics related to checkpointing blocks at mantis level

---

src/main/scala/io/iohk/ethereum/jsonrpc/server/controllers/JsonRpcBaseController.scala

Adding logs when we have a JsonRpcError.

[Chore] Logs from request with JsonRpcError

---

src/main/scala/io/iohk/ethereum/jsonrpc/JsonRpcRequest.scala
src/main/scala/io/iohk/ethereum/jsonrpc/server/controllers/JsonRpcBaseController.scala

request logged only if it doesn't have sensible information
If the request method is “personal”, we only log the next legend "sensitive information"

[Chore] request logged only if it doesn't have sensible information
